// GENERATED by packages/registry/codegen/generate.ts — DO NOT EDIT.
// Source of truth: packages/registry/measures/**/*.yaml. Run `pnpm gen`.

export type MeasurementClass = "observed" | "estimated" | "modeled" | "forecast" | "reconstructed" | "administrative";
export type AccountingConcept = "diversion" | "withdrawal" | "consumptive_use" | "depletion" | "return_flow" | "delivery" | "storage" | "evaporation" | "loss" | "allocation" | "flow" | "snowpack" | "stage" | "climate";
export type TemporalSemantics = "instantaneous" | "interval_total" | "interval_mean" | "end_of_period" | "period_max";
export type CanonicalUnit = "acre_foot" | "foot" | "cubic_foot_per_second" | "millimeter" | "percent" | "degree_celsius" | "acre" | "acre_foot_per_month" | "unitless";
export type QuantityKind = "Volume" | "Length" | "VolumeFlowRate" | "Dimensionless" | "Temperature" | "Area" | "Mass";
export type Calendar = "calendar_year" | "water_year" | "irrigation_season" | "compact_year";

export interface MeasureDef {
  readonly id: string;
  readonly label: string;
  readonly description?: string;
  readonly quantityKind: QuantityKind;
  readonly canonicalUnit: CanonicalUnit;
  readonly measurementClass: MeasurementClass;
  readonly accountingConcept: AccountingConcept;
  readonly temporalSemantics: TemporalSemantics;
  readonly grain: string;
  readonly calendar: Calendar;
  readonly spatialRef: { readonly type: string; readonly id: string };
  readonly provenance: { readonly agency: string; readonly system: string; readonly endpoint: string; readonly citation: string };
  readonly revisionStatus: string;
  readonly freshness: { readonly expectedCadence: string; readonly slaHours: number };
  readonly uncertainty?: string;
  readonly caveats: readonly string[];
  readonly notComparableWith: readonly { readonly measure: string; readonly reason: string }[];
}

export type MeasureId = "colorado.gauge.lees_ferry.discharge" | "colorado.reservoir.mead.elevation" | "colorado.reservoir.mead.release_total" | "colorado.reservoir.mead.storage" | "colorado.reservoir.powell.elevation" | "colorado.reservoir.powell.inflow_unregulated" | "colorado.reservoir.powell.release_total" | "colorado.reservoir.powell.storage" | "colorado.snow.stations.swe" | "colorado.snow.upper_basin.swe_pct_median";

export const MEASURES: Record<MeasureId, MeasureDef> = {
  "colorado.gauge.lees_ferry.discharge": {
    "id": "colorado.gauge.lees_ferry.discharge",
    "label": "Colorado River at Lees Ferry — discharge",
    "description": "Daily mean discharge at USGS gauge 09380000, the Colorado River Compact point dividing the Upper and Lower Basins. Continuous daily record since 1921-10-01. Also serves as the real-time downstream cross-check on Glen Canyon Dam releases.",
    "quantityKind": "VolumeFlowRate",
    "canonicalUnit": "cubic_foot_per_second",
    "measurementClass": "observed",
    "accountingConcept": "flow",
    "temporalSemantics": "interval_mean",
    "grain": "P1D",
    "calendar": "water_year",
    "spatialRef": {
      "type": "gauge",
      "id": "usgs.09380000"
    },
    "provenance": {
      "agency": "USGS",
      "system": "Water Data OGC API",
      "endpoint": "https://api.waterdata.usgs.gov/ogcapi/v0/collections/daily/items?monitoring_location_id=USGS-09380000&parameter_code=00060",
      "citation": "U.S. Geological Survey, National Water Information System via Water Data OGC API, site 09380000 Colorado River at Lees Ferry, AZ, parameter 00060. Accessed {access_date}."
    },
    "revisionStatus": "mixed",
    "freshness": {
      "expectedCadence": "P1D",
      "slaHours": 48
    },
    "uncertainty": "none_published",
    "caveats": [
      "Daily mean of a fluctuating hydropower-driven flow; sub-daily swings are large.",
      "Never use legacy waterservices.usgs.gov (decommissioning) or discontinued site 09379910 for this reach."
    ],
    "notComparableWith": [
      {
        "measure": "colorado.reservoir.powell.release_total",
        "reason": "Interval-mean rate (cfs) vs. interval-total volume (AF/day), measured ~15 miles apart with Paria River inflow between. Convertible only with explicit rate→volume conversion and reach caveats."
      }
    ]
  },
  "colorado.reservoir.mead.elevation": {
    "id": "colorado.reservoir.mead.elevation",
    "label": "Lake Mead pool elevation",
    "description": "Water surface elevation of Lake Mead above mean sea level. The operative variable for shortage-tier determination (via projected January 1 elevation) and the critical thresholds at 1,075 / 1,050 / 1,025 ft (tiers), ~950 ft (minimum power pool), and 895 ft (dead pool).",
    "quantityKind": "Length",
    "canonicalUnit": "foot",
    "measurementClass": "observed",
    "accountingConcept": "stage",
    "temporalSemantics": "instantaneous",
    "grain": "P1D",
    "calendar": "water_year",
    "spatialRef": {
      "type": "reservoir",
      "id": "usbr.lake_mead"
    },
    "provenance": {
      "agency": "USBR",
      "system": "RISE",
      "endpoint": "https://data.usbr.gov/rise/api/result?itemId=6123",
      "citation": "U.S. Bureau of Reclamation, RISE, Lake Mead pool elevation, catalog item 6123. Period of record from 1935-02-02. Accessed {access_date}."
    },
    "revisionStatus": "provisional",
    "freshness": {
      "expectedCadence": "P1D",
      "slaHours": 36
    },
    "uncertainty": "none_published",
    "caveats": [
      "Tier determination does not use current elevation: it uses the projected January 1 elevation from the August 24-Month Study. Displaying current elevation against tier thresholds requires that framing."
    ],
    "notComparableWith": [
      {
        "measure": "colorado.reservoir.mead.storage",
        "reason": "Elevation maps to storage only through the (re-surveyed, nonlinear) area-capacity table — never by linear scaling."
      }
    ]
  },
  "colorado.reservoir.mead.release_total": {
    "id": "colorado.reservoir.mead.release_total",
    "label": "Hoover Dam total release",
    "description": "Total daily release volume from Hoover Dam — Lake Mead outflow toward the lower river reaches, downstream diversions, and ultimately Mexico.",
    "quantityKind": "Volume",
    "canonicalUnit": "acre_foot",
    "measurementClass": "observed",
    "accountingConcept": "flow",
    "temporalSemantics": "interval_total",
    "grain": "P1D",
    "calendar": "water_year",
    "spatialRef": {
      "type": "reservoir",
      "id": "usbr.lake_mead"
    },
    "provenance": {
      "agency": "USBR",
      "system": "RISE",
      "endpoint": "https://data.usbr.gov/rise/api/result?itemId=6122",
      "citation": "U.S. Bureau of Reclamation, RISE, Hoover Dam total release (acre-feet), catalog item 6122. Accessed {access_date}."
    },
    "revisionStatus": "provisional",
    "freshness": {
      "expectedCadence": "P1D",
      "slaHours": 36
    },
    "uncertainty": "none_published",
    "caveats": [
      "RISE's Mead record has no inflow or evaporation items; Mead inflow must be derived (Powell release + intervening gains) and evaporation estimated — both as separate measures with measurement_class reflecting the derivation.",
      "Independent downstream cross-check: USGS 09421500 (below Hoover Dam)."
    ],
    "notComparableWith": []
  },
  "colorado.reservoir.mead.storage": {
    "id": "colorado.reservoir.mead.storage",
    "label": "Lake Mead storage",
    "description": "Volume of water held in Lake Mead, derived by Reclamation from measured pool elevation via the area-capacity table.",
    "quantityKind": "Volume",
    "canonicalUnit": "acre_foot",
    "measurementClass": "observed",
    "accountingConcept": "storage",
    "temporalSemantics": "instantaneous",
    "grain": "P1D",
    "calendar": "water_year",
    "spatialRef": {
      "type": "reservoir",
      "id": "usbr.lake_mead"
    },
    "provenance": {
      "agency": "USBR",
      "system": "RISE",
      "endpoint": "https://data.usbr.gov/rise/api/result?itemId=6124",
      "citation": "U.S. Bureau of Reclamation, Reclamation Information Sharing Environment (RISE), Lake Mead storage, catalog item 6124. Accessed {access_date}."
    },
    "revisionStatus": "provisional",
    "freshness": {
      "expectedCadence": "P1D",
      "slaHours": 36
    },
    "uncertainty": "none_published",
    "caveats": [
      "Storage is derived from elevation via an area-capacity table that is periodically re-surveyed; sedimentation shifts the curve over decades, so deep-historical storage values are not strictly comparable to modern ones."
    ],
    "notComparableWith": [
      {
        "measure": "colorado.upper_basin.consumptive_use",
        "reason": "Stock vs. flux. Same unit, different kind of quantity."
      },
      {
        "measure": "colorado.state.arizona.allocation",
        "reason": "Allocation is a legal entitlement, not a measurement. Meaningful only as \"use vs. entitlement\" — never as a sum or a shared total."
      }
    ]
  },
  "colorado.reservoir.powell.elevation": {
    "id": "colorado.reservoir.powell.elevation",
    "label": "Lake Powell pool elevation",
    "description": "Water surface elevation of Lake Powell above mean sea level. The operative variable for release-tier determination (via projected January 1 elevation), with critical thresholds at 3,575 / 3,525 ft (tier boundaries), 3,490 ft (minimum power pool, medium confidence), and 3,370 ft (dead pool).",
    "quantityKind": "Length",
    "canonicalUnit": "foot",
    "measurementClass": "observed",
    "accountingConcept": "stage",
    "temporalSemantics": "instantaneous",
    "grain": "P1D",
    "calendar": "water_year",
    "spatialRef": {
      "type": "reservoir",
      "id": "usbr.lake_powell"
    },
    "provenance": {
      "agency": "USBR",
      "system": "RISE",
      "endpoint": "https://data.usbr.gov/rise/api/result?itemId=508",
      "citation": "U.S. Bureau of Reclamation, RISE, Lake Powell pool elevation, catalog item 508. Accessed {access_date}."
    },
    "revisionStatus": "provisional",
    "freshness": {
      "expectedCadence": "P1D",
      "slaHours": 36
    },
    "uncertainty": "none_published",
    "caveats": [
      "Tier determination uses the projected January 1 elevation from the August 24-Month Study, not current elevation."
    ],
    "notComparableWith": []
  },
  "colorado.reservoir.powell.inflow_unregulated": {
    "id": "colorado.reservoir.powell.inflow_unregulated",
    "label": "Lake Powell unregulated inflow",
    "description": "Inflow to Lake Powell adjusted by Reclamation to remove the effects of upstream reservoir operations (Flaming Gorge, Blue Mesa, Navajo). The standard measure of what the Upper Basin actually produced, and the target variable of CBRFC seasonal forecasts.",
    "quantityKind": "Volume",
    "canonicalUnit": "acre_foot",
    "measurementClass": "estimated",
    "accountingConcept": "flow",
    "temporalSemantics": "interval_total",
    "grain": "P1D",
    "calendar": "water_year",
    "spatialRef": {
      "type": "reservoir",
      "id": "usbr.lake_powell"
    },
    "provenance": {
      "agency": "USBR",
      "system": "RISE",
      "endpoint": "https://data.usbr.gov/rise/api/result?itemId=4301",
      "citation": "U.S. Bureau of Reclamation, RISE, Lake Powell unregulated inflow, catalog item 4301. Accessed {access_date}."
    },
    "revisionStatus": "provisional",
    "freshness": {
      "expectedCadence": "P1D",
      "slaHours": 48
    },
    "uncertainty": "none_published",
    "caveats": [
      "\"Unregulated\" is a computed abstraction, not a gauge reading — it removes upstream reservoir effects but not upstream consumptive use. It is NOT natural flow. Item id 4301 assumed from catalog research; verify item 4288 vs 4301 (regulated vs unregulated, af) on first ingest."
    ],
    "notComparableWith": [
      {
        "measure": "colorado.gauge.lees_ferry.discharge_natural",
        "reason": "Unregulated inflow removes reservoir operations only; naturalized flow also adds back upstream consumptive use. Different abstractions."
      }
    ]
  },
  "colorado.reservoir.powell.release_total": {
    "id": "colorado.reservoir.powell.release_total",
    "label": "Glen Canyon Dam total release",
    "description": "Total daily release volume from Glen Canyon Dam (powerplant plus bypass and spillway), i.e. Lake Powell outflow to the Grand Canyon reach and, ultimately, Lake Mead.",
    "quantityKind": "Volume",
    "canonicalUnit": "acre_foot",
    "measurementClass": "observed",
    "accountingConcept": "flow",
    "temporalSemantics": "interval_total",
    "grain": "P1D",
    "calendar": "water_year",
    "spatialRef": {
      "type": "reservoir",
      "id": "usbr.lake_powell"
    },
    "provenance": {
      "agency": "USBR",
      "system": "RISE",
      "endpoint": "https://data.usbr.gov/rise/api/result?itemId=4354",
      "citation": "U.S. Bureau of Reclamation, RISE, Glen Canyon Dam total release (acre-feet), catalog item 4354. Accessed {access_date}."
    },
    "revisionStatus": "provisional",
    "freshness": {
      "expectedCadence": "P1D",
      "slaHours": 36
    },
    "uncertainty": "none_published",
    "caveats": [
      "Annual release volumes are set by tier rules but revisable mid-year: WY2026 was reduced from 7.48 to 6.00 MAF in April 2026 under SEIS ROD §6.E.",
      "No active USGS gauge exists immediately below the dam (09379910 was discontinued 2004-08-02); Lees Ferry (09380000), ~15 miles downstream, is the independent observational cross-check."
    ],
    "notComparableWith": [
      {
        "measure": "colorado.gauge.lees_ferry.discharge",
        "reason": "Related but not identical: Lees Ferry is ~15 miles downstream with intervening Paria River inflow and reach effects, and is an interval-mean rate (cfs) rather than an interval-total volume."
      }
    ]
  },
  "colorado.reservoir.powell.storage": {
    "id": "colorado.reservoir.powell.storage",
    "label": "Lake Powell storage",
    "description": "Volume of water held in Lake Powell, derived by Reclamation from measured pool elevation via the area-capacity table.",
    "quantityKind": "Volume",
    "canonicalUnit": "acre_foot",
    "measurementClass": "observed",
    "accountingConcept": "storage",
    "temporalSemantics": "instantaneous",
    "grain": "P1D",
    "calendar": "water_year",
    "spatialRef": {
      "type": "reservoir",
      "id": "usbr.lake_powell"
    },
    "provenance": {
      "agency": "USBR",
      "system": "RISE",
      "endpoint": "https://data.usbr.gov/rise/api/result?itemId=509",
      "citation": "U.S. Bureau of Reclamation, RISE, Lake Powell storage, catalog item 509. Accessed {access_date}."
    },
    "revisionStatus": "provisional",
    "freshness": {
      "expectedCadence": "P1D",
      "slaHours": 36
    },
    "uncertainty": "none_published",
    "caveats": [
      "Sedimentation since 1963 has reduced actual capacity below the nominal 24.32 MAF; percent-full figures depend on which capacity survey is used."
    ],
    "notComparableWith": [
      {
        "measure": "colorado.upper_basin.consumptive_use",
        "reason": "Stock vs. flux. Same unit, different kind of quantity."
      }
    ]
  },
  "colorado.snow.stations.swe": {
    "id": "colorado.snow.stations.swe",
    "label": "SNOTEL station snow water equivalent",
    "description": "Daily snow water equivalent at individual SNOTEL stations in the Upper Colorado Basin HUCs. The raw input to the basin percent-of-median rollup and the hydrology model's SWE features. Station dimension carried in geography_id (one observation row per station per day).",
    "quantityKind": "Length",
    "canonicalUnit": "millimeter",
    "measurementClass": "observed",
    "accountingConcept": "snowpack",
    "temporalSemantics": "instantaneous",
    "grain": "P1D",
    "calendar": "water_year",
    "spatialRef": {
      "type": "basin",
      "id": "colorado.upper_basin"
    },
    "provenance": {
      "agency": "USDA-NRCS",
      "system": "AWDB REST",
      "endpoint": "https://wcc.sc.egov.usda.gov/awdbRestApi/services/v1/data",
      "citation": "USDA Natural Resources Conservation Service, Air and Water Database (AWDB), SNOTEL network, element WTEQ. Accessed {access_date}."
    },
    "revisionStatus": "provisional",
    "freshness": {
      "expectedCadence": "P1D",
      "slaHours": 48
    },
    "uncertainty": "none_published",
    "caveats": [
      "Source unit is inches; converted to canonical millimeters at ingest.",
      "Station set changes over time (new stations, discontinuations); the stations endpoint's beginDate/endDate and HUC membership are synced as a dimension, not assumed static."
    ],
    "notComparableWith": []
  },
  "colorado.snow.upper_basin.swe_pct_median": {
    "id": "colorado.snow.upper_basin.swe_pct_median",
    "label": "Upper Basin snowpack — percent of median SWE",
    "description": "Snow water equivalent across Upper Colorado Basin SNOTEL stations as a percent of the 1991–2020 median for the date. COMPUTED BY US from station-level AWDB data plus HUC membership — NRCS publishes this only as a map product, not an API. Methodology replicates NRCS practice; deviations are documented in the computation module and surfaced here.",
    "quantityKind": "Dimensionless",
    "canonicalUnit": "percent",
    "measurementClass": "estimated",
    "accountingConcept": "snowpack",
    "temporalSemantics": "instantaneous",
    "grain": "P1D",
    "calendar": "water_year",
    "spatialRef": {
      "type": "basin",
      "id": "colorado.upper_basin"
    },
    "provenance": {
      "agency": "USDA-NRCS (stations); Basin (aggregation)",
      "system": "AWDB REST + basin computation",
      "endpoint": "https://wcc.sc.egov.usda.gov/awdbRestApi/services/v1/data",
      "citation": "Computed from USDA NRCS AWDB SNOTEL station data (snow water equivalent, element WTEQ) aggregated over Upper Colorado Basin HUCs against 1991–2020 station medians. Basin project computation. Accessed {access_date}."
    },
    "revisionStatus": "provisional",
    "freshness": {
      "expectedCadence": "P1D",
      "slaHours": 48
    },
    "uncertainty": "method_range",
    "caveats": [
      "This is OUR aggregation, not the NRCS number. Reconciliation against the NRCS map product is a standing asset check with a stated tolerance; divergence beyond tolerance fails the pipeline, not silently ships.",
      "Percent-of-median is undefined when the median approaches zero (early autumn, mid-summer); the computation returns null outside the snow season rather than an unstable ratio. Missing is not zero.",
      "SNOTEL coverage begins in the late 1970s; the network densified over time."
    ],
    "notComparableWith": [
      {
        "measure": "colorado.reservoir.powell.inflow_unregulated",
        "reason": "Snowpack percent does not map linearly to runoff volume — runoff efficiency varies with temperature, soil moisture, and dust; that relationship is exactly what the hydrology model estimates."
      }
    ]
  },
};

/**
 * Guard: measures whose accounting concepts differ may not be summed or
 * directly compared. Returns the declared human-readable reason when the
 * pair is explicitly marked incomparable, or a generic concept-mismatch
 * reason; null when the combination is allowed.
 */
export function incomparabilityReason(a: MeasureId, b: MeasureId): string | null {
  if (a === b) return null;
  const ma = MEASURES[a];
  const mb = MEASURES[b];
  const declared =
    ma.notComparableWith.find((e) => e.measure === b) ??
    mb.notComparableWith.find((e) => e.measure === a);
  if (declared) return declared.reason;
  if (ma.accountingConcept !== mb.accountingConcept)
    return `Different accounting concepts: ${ma.accountingConcept} vs ${mb.accountingConcept}. Combining them requires a declared bridge.`;
  if (ma.temporalSemantics !== mb.temporalSemantics)
    return `Different temporal semantics: ${ma.temporalSemantics} vs ${mb.temporalSemantics}. Aggregation across them is undefined.`;
  return null;
}
