// GENERATED by packages/model/basin_model/export_rulebook.py — DO NOT EDIT.
// Source of truth: packages/model/basin_model/rulebook.py
// Regenerate: python -m basin_model.export_rulebook
// VECTORS are determinations computed by the Python engine; the TS
// evaluator must reproduce them exactly (see verify-rules.ts).

export const RULEBOOK_DATA = {
  "rulebook": {
    "version": "v2007-ig-dcp",
    "label": "2007 Interim Guidelines + 2019 Lower Basin DCP + Minute 323",
    "authority": "2007 ROD, Colorado River Interim Guidelines for Lower Basin Shortages (\u00a7XI.G.2.D; trigger \u00a7XI.F.1) \u00b7 Lower Basin DCP Agreement, Exhibit 1 'LBOps' (\u00a7III.B\u2013C) \u00b7 IBWC Minute 323 (\u00a7III.A, \u00a7IV)",
    "effectiveFrom": "2008-01-01",
    "effectiveTo": "2026-09-30",
    "status": "in_force",
    "trigger": "Projected January 1 Lake Mead elevation from the AUGUST 24-Month Study, most probable inflows. Not a current reading.",
    "criticalElevations": {
      "powell_dead_pool": 3370.0,
      "powell_min_power_pool": 3490.0,
      "powell_full_pool": 3700.0,
      "mead_dead_pool": 895.0,
      "mead_min_power_pool": 950.0,
      "mead_full_pool": 1229.0,
      "mexico_recovery_threshold": 1110.0
    },
    "notes": [
      "Minute 323 \u00a7IV savings are RECOVERABLE by Mexico when the August 24-Month Study projects Mead \u2265 1,110 ft on January 1; \u00a7III.A reductions are not.",
      "Total annual scheduled delivery to Mexico may not exceed 1,700,000 AF.",
      "Release volumes are revisable within the water year: WY2026 Powell release was set at 7.48 MAF in Aug 2025 and reduced to 6.00 MAF on 2026-04-17 under SEIS ROD \u00a76.E.",
      "Powell minimum power pool (3,490 ft) and both Mead critical elevations are MEDIUM confidence \u2014 convergent secondary sources, not confirmed in a primary Reclamation document."
    ],
    "powellTiers": [
      {
        "name": "Equalization Tier",
        "band": {
          "upper": null,
          "lower": 3666.0,
          "upperInclusive": true,
          "lowerInclusive": true,
          "wording": "at or above the year-specific Equalization Elevation"
        },
        "releaseAf": null,
        "balancingRange": [
          8230000,
          12000000
        ],
        "meadBelow": null,
        "meadBelowReleaseAf": null,
        "meadBelowBalancingRange": null,
        "note": "Release >8.23 MAF to equalize storage with Lake Mead or avoid spills. The trigger is a year-specific table in the Guidelines (historical examples 3,636\u20133,666 ft), approximated here by its upper value \u2014 a scenario reaching this tier should consult the table for the specific year."
      },
      {
        "name": "Upper Elevation Balancing Tier",
        "band": {
          "upper": 3666.0,
          "lower": 3575.0,
          "upperInclusive": false,
          "lowerInclusive": true,
          "wording": "below the Equalization Elevation and at or above 3,575 ft"
        },
        "releaseAf": 8230000,
        "balancingRange": null,
        "meadBelow": 1075.0,
        "meadBelowReleaseAf": null,
        "meadBelowBalancingRange": [
          7000000,
          9000000
        ],
        "note": "Release 8.23 MAF; if Lake Mead is below 1,075 ft, balance contents within 7.0\u20139.0 MAF. May shift back to Equalization if the April 24-Month Study projects reaching the equalization elevation."
      },
      {
        "name": "Mid-Elevation Release Tier",
        "band": {
          "upper": 3575.0,
          "lower": 3525.0,
          "upperInclusive": false,
          "lowerInclusive": true,
          "wording": "below 3,575 ft and at or above 3,525 ft"
        },
        "releaseAf": 7480000,
        "balancingRange": null,
        "meadBelow": 1025.0,
        "meadBelowReleaseAf": 8230000,
        "meadBelowBalancingRange": null,
        "note": "Release 7.48 MAF; if Lake Mead is below 1,025 ft, release 8.23 MAF instead."
      },
      {
        "name": "Lower Elevation Balancing Tier",
        "band": {
          "upper": 3525.0,
          "lower": null,
          "upperInclusive": false,
          "lowerInclusive": false,
          "wording": "below 3,525 ft"
        },
        "releaseAf": null,
        "balancingRange": [
          7000000,
          9500000
        ],
        "meadBelow": null,
        "meadBelowReleaseAf": null,
        "meadBelowBalancingRange": null,
        "note": "Balance contents within 7.0\u20139.5 MAF."
      }
    ],
    "meadReductions": [
      {
        "party": "arizona",
        "kind": "ig_shortage",
        "band": {
          "upper": 1075.0,
          "lower": 1050.0,
          "upperInclusive": true,
          "lowerInclusive": true,
          "wording": "at or below 1,075 and at or above 1,050"
        },
        "acreFeet": 320000
      },
      {
        "party": "nevada",
        "kind": "ig_shortage",
        "band": {
          "upper": 1075.0,
          "lower": 1050.0,
          "upperInclusive": true,
          "lowerInclusive": true,
          "wording": "at or below 1,075 and at or above 1,050"
        },
        "acreFeet": 13000
      },
      {
        "party": "arizona",
        "kind": "ig_shortage",
        "band": {
          "upper": 1050.0,
          "lower": 1025.0,
          "upperInclusive": false,
          "lowerInclusive": true,
          "wording": "below 1,050 and at or above 1,025"
        },
        "acreFeet": 400000
      },
      {
        "party": "nevada",
        "kind": "ig_shortage",
        "band": {
          "upper": 1050.0,
          "lower": 1025.0,
          "upperInclusive": false,
          "lowerInclusive": true,
          "wording": "below 1,050 and at or above 1,025"
        },
        "acreFeet": 17000
      },
      {
        "party": "arizona",
        "kind": "ig_shortage",
        "band": {
          "upper": 1025.0,
          "lower": null,
          "upperInclusive": false,
          "lowerInclusive": false,
          "wording": "below 1,025"
        },
        "acreFeet": 480000
      },
      {
        "party": "nevada",
        "kind": "ig_shortage",
        "band": {
          "upper": 1025.0,
          "lower": null,
          "upperInclusive": false,
          "lowerInclusive": false,
          "wording": "below 1,025"
        },
        "acreFeet": 20000
      },
      {
        "party": "arizona",
        "kind": "dcp_contribution",
        "band": {
          "upper": 1090.0,
          "lower": 1045.0,
          "upperInclusive": true,
          "lowerInclusive": false,
          "wording": "above 1,045 and at or below 1,090"
        },
        "acreFeet": 192000
      },
      {
        "party": "arizona",
        "kind": "dcp_contribution",
        "band": {
          "upper": 1045.0,
          "lower": null,
          "upperInclusive": true,
          "lowerInclusive": false,
          "wording": "at or below 1,045"
        },
        "acreFeet": 240000
      },
      {
        "party": "nevada",
        "kind": "dcp_contribution",
        "band": {
          "upper": 1090.0,
          "lower": 1045.0,
          "upperInclusive": true,
          "lowerInclusive": false,
          "wording": "above 1,045 and at or below 1,090"
        },
        "acreFeet": 8000
      },
      {
        "party": "nevada",
        "kind": "dcp_contribution",
        "band": {
          "upper": 1045.0,
          "lower": null,
          "upperInclusive": true,
          "lowerInclusive": false,
          "wording": "at or below 1,045"
        },
        "acreFeet": 10000
      },
      {
        "party": "california",
        "kind": "dcp_contribution",
        "band": {
          "upper": 1045.0,
          "lower": 1040.0,
          "upperInclusive": true,
          "lowerInclusive": false,
          "wording": "above 1,040 and at or below 1,045"
        },
        "acreFeet": 200000
      },
      {
        "party": "california",
        "kind": "dcp_contribution",
        "band": {
          "upper": 1040.0,
          "lower": 1035.0,
          "upperInclusive": true,
          "lowerInclusive": false,
          "wording": "above 1,035 and at or below 1,040"
        },
        "acreFeet": 250000
      },
      {
        "party": "california",
        "kind": "dcp_contribution",
        "band": {
          "upper": 1035.0,
          "lower": 1030.0,
          "upperInclusive": true,
          "lowerInclusive": false,
          "wording": "above 1,030 and at or below 1,035"
        },
        "acreFeet": 300000
      },
      {
        "party": "california",
        "kind": "dcp_contribution",
        "band": {
          "upper": 1030.0,
          "lower": null,
          "upperInclusive": true,
          "lowerInclusive": false,
          "wording": "at or below 1,030"
        },
        "acreFeet": 350000
      },
      {
        "party": "mexico",
        "kind": "treaty_reduction",
        "band": {
          "upper": 1075.0,
          "lower": 1050.0,
          "upperInclusive": true,
          "lowerInclusive": true,
          "wording": "at or below 1,075 and at or above 1,050"
        },
        "acreFeet": 50000
      },
      {
        "party": "mexico",
        "kind": "treaty_reduction",
        "band": {
          "upper": 1050.0,
          "lower": 1025.0,
          "upperInclusive": false,
          "lowerInclusive": true,
          "wording": "below 1,050 and at or above 1,025"
        },
        "acreFeet": 70000
      },
      {
        "party": "mexico",
        "kind": "treaty_reduction",
        "band": {
          "upper": 1025.0,
          "lower": null,
          "upperInclusive": false,
          "lowerInclusive": false,
          "wording": "below 1,025"
        },
        "acreFeet": 125000
      },
      {
        "party": "mexico",
        "kind": "treaty_savings",
        "band": {
          "upper": 1090.0,
          "lower": 1075.0,
          "upperInclusive": true,
          "lowerInclusive": false,
          "wording": "at or below 1,090 and above 1,075"
        },
        "acreFeet": 41000
      },
      {
        "party": "mexico",
        "kind": "treaty_savings",
        "band": {
          "upper": 1075.0,
          "lower": 1050.0,
          "upperInclusive": true,
          "lowerInclusive": false,
          "wording": "at or below 1,075 and above 1,050"
        },
        "acreFeet": 30000
      },
      {
        "party": "mexico",
        "kind": "treaty_savings",
        "band": {
          "upper": 1050.0,
          "lower": 1045.0,
          "upperInclusive": true,
          "lowerInclusive": false,
          "wording": "at or below 1,050 and above 1,045"
        },
        "acreFeet": 34000
      },
      {
        "party": "mexico",
        "kind": "treaty_savings",
        "band": {
          "upper": 1045.0,
          "lower": 1040.0,
          "upperInclusive": true,
          "lowerInclusive": false,
          "wording": "at or below 1,045 and above 1,040"
        },
        "acreFeet": 76000
      },
      {
        "party": "mexico",
        "kind": "treaty_savings",
        "band": {
          "upper": 1040.0,
          "lower": 1035.0,
          "upperInclusive": true,
          "lowerInclusive": false,
          "wording": "at or below 1,040 and above 1,035"
        },
        "acreFeet": 84000
      },
      {
        "party": "mexico",
        "kind": "treaty_savings",
        "band": {
          "upper": 1035.0,
          "lower": 1030.0,
          "upperInclusive": true,
          "lowerInclusive": false,
          "wording": "at or below 1,035 and above 1,030"
        },
        "acreFeet": 92000
      },
      {
        "party": "mexico",
        "kind": "treaty_savings",
        "band": {
          "upper": 1030.0,
          "lower": 1025.0,
          "upperInclusive": true,
          "lowerInclusive": false,
          "wording": "at or below 1,030 and above 1,025"
        },
        "acreFeet": 101000
      },
      {
        "party": "mexico",
        "kind": "treaty_savings",
        "band": {
          "upper": 1025.0,
          "lower": null,
          "upperInclusive": true,
          "lowerInclusive": false,
          "wording": "at or below 1,025"
        },
        "acreFeet": 150000
      }
    ]
  },
  "vectors": {
    "mead": [
      {
        "elevation": 895.0,
        "tierLabel": "Tier 3 shortage",
        "arizona": 720000.0,
        "nevada": 30000.0,
        "california": 350000.0,
        "mexicoReduction": 125000.0,
        "mexicoSavings": 150000.0,
        "usLowerBasin": 1100000.0,
        "totalIncludingSavings": 1375000.0
      },
      {
        "elevation": 950.0,
        "tierLabel": "Tier 3 shortage",
        "arizona": 720000.0,
        "nevada": 30000.0,
        "california": 350000.0,
        "mexicoReduction": 125000.0,
        "mexicoSavings": 150000.0,
        "usLowerBasin": 1100000.0,
        "totalIncludingSavings": 1375000.0
      },
      {
        "elevation": 1000.0,
        "tierLabel": "Tier 3 shortage",
        "arizona": 720000.0,
        "nevada": 30000.0,
        "california": 350000.0,
        "mexicoReduction": 125000.0,
        "mexicoSavings": 150000.0,
        "usLowerBasin": 1100000.0,
        "totalIncludingSavings": 1375000.0
      },
      {
        "elevation": 1024.99,
        "tierLabel": "Tier 3 shortage",
        "arizona": 720000.0,
        "nevada": 30000.0,
        "california": 350000.0,
        "mexicoReduction": 125000.0,
        "mexicoSavings": 150000.0,
        "usLowerBasin": 1100000.0,
        "totalIncludingSavings": 1375000.0
      },
      {
        "elevation": 1025.0,
        "tierLabel": "Tier 2 shortage",
        "arizona": 640000.0,
        "nevada": 27000.0,
        "california": 350000.0,
        "mexicoReduction": 70000.0,
        "mexicoSavings": 150000.0,
        "usLowerBasin": 1017000.0,
        "totalIncludingSavings": 1237000.0
      },
      {
        "elevation": 1025.01,
        "tierLabel": "Tier 2 shortage",
        "arizona": 640000.0,
        "nevada": 27000.0,
        "california": 350000.0,
        "mexicoReduction": 70000.0,
        "mexicoSavings": 101000.0,
        "usLowerBasin": 1017000.0,
        "totalIncludingSavings": 1188000.0
      },
      {
        "elevation": 1029.99,
        "tierLabel": "Tier 2 shortage",
        "arizona": 640000.0,
        "nevada": 27000.0,
        "california": 350000.0,
        "mexicoReduction": 70000.0,
        "mexicoSavings": 101000.0,
        "usLowerBasin": 1017000.0,
        "totalIncludingSavings": 1188000.0
      },
      {
        "elevation": 1030.0,
        "tierLabel": "Tier 2 shortage",
        "arizona": 640000.0,
        "nevada": 27000.0,
        "california": 350000.0,
        "mexicoReduction": 70000.0,
        "mexicoSavings": 101000.0,
        "usLowerBasin": 1017000.0,
        "totalIncludingSavings": 1188000.0
      },
      {
        "elevation": 1030.01,
        "tierLabel": "Tier 2 shortage",
        "arizona": 640000.0,
        "nevada": 27000.0,
        "california": 300000.0,
        "mexicoReduction": 70000.0,
        "mexicoSavings": 92000.0,
        "usLowerBasin": 967000.0,
        "totalIncludingSavings": 1129000.0
      },
      {
        "elevation": 1034.99,
        "tierLabel": "Tier 2 shortage",
        "arizona": 640000.0,
        "nevada": 27000.0,
        "california": 300000.0,
        "mexicoReduction": 70000.0,
        "mexicoSavings": 92000.0,
        "usLowerBasin": 967000.0,
        "totalIncludingSavings": 1129000.0
      },
      {
        "elevation": 1035.0,
        "tierLabel": "Tier 2 shortage",
        "arizona": 640000.0,
        "nevada": 27000.0,
        "california": 300000.0,
        "mexicoReduction": 70000.0,
        "mexicoSavings": 92000.0,
        "usLowerBasin": 967000.0,
        "totalIncludingSavings": 1129000.0
      },
      {
        "elevation": 1035.01,
        "tierLabel": "Tier 2 shortage",
        "arizona": 640000.0,
        "nevada": 27000.0,
        "california": 250000.0,
        "mexicoReduction": 70000.0,
        "mexicoSavings": 84000.0,
        "usLowerBasin": 917000.0,
        "totalIncludingSavings": 1071000.0
      },
      {
        "elevation": 1039.99,
        "tierLabel": "Tier 2 shortage",
        "arizona": 640000.0,
        "nevada": 27000.0,
        "california": 250000.0,
        "mexicoReduction": 70000.0,
        "mexicoSavings": 84000.0,
        "usLowerBasin": 917000.0,
        "totalIncludingSavings": 1071000.0
      },
      {
        "elevation": 1040.0,
        "tierLabel": "Tier 2 shortage",
        "arizona": 640000.0,
        "nevada": 27000.0,
        "california": 250000.0,
        "mexicoReduction": 70000.0,
        "mexicoSavings": 84000.0,
        "usLowerBasin": 917000.0,
        "totalIncludingSavings": 1071000.0
      },
      {
        "elevation": 1040.01,
        "tierLabel": "Tier 2 shortage",
        "arizona": 640000.0,
        "nevada": 27000.0,
        "california": 200000.0,
        "mexicoReduction": 70000.0,
        "mexicoSavings": 76000.0,
        "usLowerBasin": 867000.0,
        "totalIncludingSavings": 1013000.0
      },
      {
        "elevation": 1041.1,
        "tierLabel": "Tier 2 shortage",
        "arizona": 640000.0,
        "nevada": 27000.0,
        "california": 200000.0,
        "mexicoReduction": 70000.0,
        "mexicoSavings": 76000.0,
        "usLowerBasin": 867000.0,
        "totalIncludingSavings": 1013000.0
      },
      {
        "elevation": 1044.99,
        "tierLabel": "Tier 2 shortage",
        "arizona": 640000.0,
        "nevada": 27000.0,
        "california": 200000.0,
        "mexicoReduction": 70000.0,
        "mexicoSavings": 76000.0,
        "usLowerBasin": 867000.0,
        "totalIncludingSavings": 1013000.0
      },
      {
        "elevation": 1045.0,
        "tierLabel": "Tier 2 shortage",
        "arizona": 640000.0,
        "nevada": 27000.0,
        "california": 200000.0,
        "mexicoReduction": 70000.0,
        "mexicoSavings": 76000.0,
        "usLowerBasin": 867000.0,
        "totalIncludingSavings": 1013000.0
      },
      {
        "elevation": 1045.01,
        "tierLabel": "Tier 2 shortage",
        "arizona": 592000.0,
        "nevada": 25000.0,
        "california": 0,
        "mexicoReduction": 70000.0,
        "mexicoSavings": 34000.0,
        "usLowerBasin": 617000.0,
        "totalIncludingSavings": 721000.0
      },
      {
        "elevation": 1049.99,
        "tierLabel": "Tier 2 shortage",
        "arizona": 592000.0,
        "nevada": 25000.0,
        "california": 0,
        "mexicoReduction": 70000.0,
        "mexicoSavings": 34000.0,
        "usLowerBasin": 617000.0,
        "totalIncludingSavings": 721000.0
      },
      {
        "elevation": 1050.0,
        "tierLabel": "Tier 1 shortage",
        "arizona": 512000.0,
        "nevada": 21000.0,
        "california": 0,
        "mexicoReduction": 50000.0,
        "mexicoSavings": 34000.0,
        "usLowerBasin": 533000.0,
        "totalIncludingSavings": 617000.0
      },
      {
        "elevation": 1050.01,
        "tierLabel": "Tier 1 shortage",
        "arizona": 512000.0,
        "nevada": 21000.0,
        "california": 0,
        "mexicoReduction": 50000.0,
        "mexicoSavings": 30000.0,
        "usLowerBasin": 533000.0,
        "totalIncludingSavings": 613000.0
      },
      {
        "elevation": 1074.99,
        "tierLabel": "Tier 1 shortage",
        "arizona": 512000.0,
        "nevada": 21000.0,
        "california": 0,
        "mexicoReduction": 50000.0,
        "mexicoSavings": 30000.0,
        "usLowerBasin": 533000.0,
        "totalIncludingSavings": 613000.0
      },
      {
        "elevation": 1075.0,
        "tierLabel": "Tier 1 shortage",
        "arizona": 512000.0,
        "nevada": 21000.0,
        "california": 0,
        "mexicoReduction": 50000.0,
        "mexicoSavings": 30000.0,
        "usLowerBasin": 533000.0,
        "totalIncludingSavings": 613000.0
      },
      {
        "elevation": 1075.01,
        "tierLabel": "Tier 0 (DCP contributions)",
        "arizona": 192000.0,
        "nevada": 8000.0,
        "california": 0,
        "mexicoReduction": 0,
        "mexicoSavings": 41000.0,
        "usLowerBasin": 200000.0,
        "totalIncludingSavings": 241000.0
      },
      {
        "elevation": 1089.99,
        "tierLabel": "Tier 0 (DCP contributions)",
        "arizona": 192000.0,
        "nevada": 8000.0,
        "california": 0,
        "mexicoReduction": 0,
        "mexicoSavings": 41000.0,
        "usLowerBasin": 200000.0,
        "totalIncludingSavings": 241000.0
      },
      {
        "elevation": 1090.0,
        "tierLabel": "Tier 0 (DCP contributions)",
        "arizona": 192000.0,
        "nevada": 8000.0,
        "california": 0,
        "mexicoReduction": 0,
        "mexicoSavings": 41000.0,
        "usLowerBasin": 200000.0,
        "totalIncludingSavings": 241000.0
      },
      {
        "elevation": 1090.01,
        "tierLabel": "Normal / surplus condition",
        "arizona": 0,
        "nevada": 0,
        "california": 0,
        "mexicoReduction": 0,
        "mexicoSavings": 0,
        "usLowerBasin": 0,
        "totalIncludingSavings": 0
      },
      {
        "elevation": 1100.0,
        "tierLabel": "Normal / surplus condition",
        "arizona": 0,
        "nevada": 0,
        "california": 0,
        "mexicoReduction": 0,
        "mexicoSavings": 0,
        "usLowerBasin": 0,
        "totalIncludingSavings": 0
      },
      {
        "elevation": 1150.0,
        "tierLabel": "Normal / surplus condition",
        "arizona": 0,
        "nevada": 0,
        "california": 0,
        "mexicoReduction": 0,
        "mexicoSavings": 0,
        "usLowerBasin": 0,
        "totalIncludingSavings": 0
      },
      {
        "elevation": 1229.0,
        "tierLabel": "Normal / surplus condition",
        "arizona": 0,
        "nevada": 0,
        "california": 0,
        "mexicoReduction": 0,
        "mexicoSavings": 0,
        "usLowerBasin": 0,
        "totalIncludingSavings": 0
      }
    ],
    "powell": [
      {
        "powellElevation": 3370.0,
        "meadElevation": 1100.0,
        "tier": "Lower Elevation Balancing Tier",
        "releaseAf": null,
        "balancingRange": [
          7000000,
          9500000
        ],
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 8250000.0
      },
      {
        "powellElevation": 3370.0,
        "meadElevation": 1060.0,
        "tier": "Lower Elevation Balancing Tier",
        "releaseAf": null,
        "balancingRange": [
          7000000,
          9500000
        ],
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 8250000.0
      },
      {
        "powellElevation": 3370.0,
        "meadElevation": 1020.0,
        "tier": "Lower Elevation Balancing Tier",
        "releaseAf": null,
        "balancingRange": [
          7000000,
          9500000
        ],
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 8250000.0
      },
      {
        "powellElevation": 3400.0,
        "meadElevation": 1100.0,
        "tier": "Lower Elevation Balancing Tier",
        "releaseAf": null,
        "balancingRange": [
          7000000,
          9500000
        ],
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 8250000.0
      },
      {
        "powellElevation": 3400.0,
        "meadElevation": 1060.0,
        "tier": "Lower Elevation Balancing Tier",
        "releaseAf": null,
        "balancingRange": [
          7000000,
          9500000
        ],
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 8250000.0
      },
      {
        "powellElevation": 3400.0,
        "meadElevation": 1020.0,
        "tier": "Lower Elevation Balancing Tier",
        "releaseAf": null,
        "balancingRange": [
          7000000,
          9500000
        ],
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 8250000.0
      },
      {
        "powellElevation": 3490.0,
        "meadElevation": 1100.0,
        "tier": "Lower Elevation Balancing Tier",
        "releaseAf": null,
        "balancingRange": [
          7000000,
          9500000
        ],
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 8250000.0
      },
      {
        "powellElevation": 3490.0,
        "meadElevation": 1060.0,
        "tier": "Lower Elevation Balancing Tier",
        "releaseAf": null,
        "balancingRange": [
          7000000,
          9500000
        ],
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 8250000.0
      },
      {
        "powellElevation": 3490.0,
        "meadElevation": 1020.0,
        "tier": "Lower Elevation Balancing Tier",
        "releaseAf": null,
        "balancingRange": [
          7000000,
          9500000
        ],
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 8250000.0
      },
      {
        "powellElevation": 3522.27,
        "meadElevation": 1100.0,
        "tier": "Lower Elevation Balancing Tier",
        "releaseAf": null,
        "balancingRange": [
          7000000,
          9500000
        ],
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 8250000.0
      },
      {
        "powellElevation": 3522.27,
        "meadElevation": 1060.0,
        "tier": "Lower Elevation Balancing Tier",
        "releaseAf": null,
        "balancingRange": [
          7000000,
          9500000
        ],
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 8250000.0
      },
      {
        "powellElevation": 3522.27,
        "meadElevation": 1020.0,
        "tier": "Lower Elevation Balancing Tier",
        "releaseAf": null,
        "balancingRange": [
          7000000,
          9500000
        ],
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 8250000.0
      },
      {
        "powellElevation": 3524.99,
        "meadElevation": 1100.0,
        "tier": "Lower Elevation Balancing Tier",
        "releaseAf": null,
        "balancingRange": [
          7000000,
          9500000
        ],
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 8250000.0
      },
      {
        "powellElevation": 3524.99,
        "meadElevation": 1060.0,
        "tier": "Lower Elevation Balancing Tier",
        "releaseAf": null,
        "balancingRange": [
          7000000,
          9500000
        ],
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 8250000.0
      },
      {
        "powellElevation": 3524.99,
        "meadElevation": 1020.0,
        "tier": "Lower Elevation Balancing Tier",
        "releaseAf": null,
        "balancingRange": [
          7000000,
          9500000
        ],
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 8250000.0
      },
      {
        "powellElevation": 3525.0,
        "meadElevation": 1100.0,
        "tier": "Mid-Elevation Release Tier",
        "releaseAf": 7480000,
        "balancingRange": null,
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 7480000
      },
      {
        "powellElevation": 3525.0,
        "meadElevation": 1060.0,
        "tier": "Mid-Elevation Release Tier",
        "releaseAf": 7480000,
        "balancingRange": null,
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 7480000
      },
      {
        "powellElevation": 3525.0,
        "meadElevation": 1020.0,
        "tier": "Mid-Elevation Release Tier",
        "releaseAf": 8230000,
        "balancingRange": null,
        "meadOverrideApplied": true,
        "releaseOrMidpoint": 8230000
      },
      {
        "powellElevation": 3525.01,
        "meadElevation": 1100.0,
        "tier": "Mid-Elevation Release Tier",
        "releaseAf": 7480000,
        "balancingRange": null,
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 7480000
      },
      {
        "powellElevation": 3525.01,
        "meadElevation": 1060.0,
        "tier": "Mid-Elevation Release Tier",
        "releaseAf": 7480000,
        "balancingRange": null,
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 7480000
      },
      {
        "powellElevation": 3525.01,
        "meadElevation": 1020.0,
        "tier": "Mid-Elevation Release Tier",
        "releaseAf": 8230000,
        "balancingRange": null,
        "meadOverrideApplied": true,
        "releaseOrMidpoint": 8230000
      },
      {
        "powellElevation": 3574.99,
        "meadElevation": 1100.0,
        "tier": "Mid-Elevation Release Tier",
        "releaseAf": 7480000,
        "balancingRange": null,
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 7480000
      },
      {
        "powellElevation": 3574.99,
        "meadElevation": 1060.0,
        "tier": "Mid-Elevation Release Tier",
        "releaseAf": 7480000,
        "balancingRange": null,
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 7480000
      },
      {
        "powellElevation": 3574.99,
        "meadElevation": 1020.0,
        "tier": "Mid-Elevation Release Tier",
        "releaseAf": 8230000,
        "balancingRange": null,
        "meadOverrideApplied": true,
        "releaseOrMidpoint": 8230000
      },
      {
        "powellElevation": 3575.0,
        "meadElevation": 1100.0,
        "tier": "Upper Elevation Balancing Tier",
        "releaseAf": 8230000,
        "balancingRange": null,
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 8230000
      },
      {
        "powellElevation": 3575.0,
        "meadElevation": 1060.0,
        "tier": "Upper Elevation Balancing Tier",
        "releaseAf": null,
        "balancingRange": [
          7000000,
          9000000
        ],
        "meadOverrideApplied": true,
        "releaseOrMidpoint": 8000000.0
      },
      {
        "powellElevation": 3575.0,
        "meadElevation": 1020.0,
        "tier": "Upper Elevation Balancing Tier",
        "releaseAf": null,
        "balancingRange": [
          7000000,
          9000000
        ],
        "meadOverrideApplied": true,
        "releaseOrMidpoint": 8000000.0
      },
      {
        "powellElevation": 3575.01,
        "meadElevation": 1100.0,
        "tier": "Upper Elevation Balancing Tier",
        "releaseAf": 8230000,
        "balancingRange": null,
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 8230000
      },
      {
        "powellElevation": 3575.01,
        "meadElevation": 1060.0,
        "tier": "Upper Elevation Balancing Tier",
        "releaseAf": null,
        "balancingRange": [
          7000000,
          9000000
        ],
        "meadOverrideApplied": true,
        "releaseOrMidpoint": 8000000.0
      },
      {
        "powellElevation": 3575.01,
        "meadElevation": 1020.0,
        "tier": "Upper Elevation Balancing Tier",
        "releaseAf": null,
        "balancingRange": [
          7000000,
          9000000
        ],
        "meadOverrideApplied": true,
        "releaseOrMidpoint": 8000000.0
      },
      {
        "powellElevation": 3600.0,
        "meadElevation": 1100.0,
        "tier": "Upper Elevation Balancing Tier",
        "releaseAf": 8230000,
        "balancingRange": null,
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 8230000
      },
      {
        "powellElevation": 3600.0,
        "meadElevation": 1060.0,
        "tier": "Upper Elevation Balancing Tier",
        "releaseAf": null,
        "balancingRange": [
          7000000,
          9000000
        ],
        "meadOverrideApplied": true,
        "releaseOrMidpoint": 8000000.0
      },
      {
        "powellElevation": 3600.0,
        "meadElevation": 1020.0,
        "tier": "Upper Elevation Balancing Tier",
        "releaseAf": null,
        "balancingRange": [
          7000000,
          9000000
        ],
        "meadOverrideApplied": true,
        "releaseOrMidpoint": 8000000.0
      },
      {
        "powellElevation": 3666.0,
        "meadElevation": 1100.0,
        "tier": "Equalization Tier",
        "releaseAf": null,
        "balancingRange": [
          8230000,
          12000000
        ],
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 10115000.0
      },
      {
        "powellElevation": 3666.0,
        "meadElevation": 1060.0,
        "tier": "Equalization Tier",
        "releaseAf": null,
        "balancingRange": [
          8230000,
          12000000
        ],
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 10115000.0
      },
      {
        "powellElevation": 3666.0,
        "meadElevation": 1020.0,
        "tier": "Equalization Tier",
        "releaseAf": null,
        "balancingRange": [
          8230000,
          12000000
        ],
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 10115000.0
      },
      {
        "powellElevation": 3700.0,
        "meadElevation": 1100.0,
        "tier": "Equalization Tier",
        "releaseAf": null,
        "balancingRange": [
          8230000,
          12000000
        ],
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 10115000.0
      },
      {
        "powellElevation": 3700.0,
        "meadElevation": 1060.0,
        "tier": "Equalization Tier",
        "releaseAf": null,
        "balancingRange": [
          8230000,
          12000000
        ],
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 10115000.0
      },
      {
        "powellElevation": 3700.0,
        "meadElevation": 1020.0,
        "tier": "Equalization Tier",
        "releaseAf": null,
        "balancingRange": [
          8230000,
          12000000
        ],
        "meadOverrideApplied": false,
        "releaseOrMidpoint": 10115000.0
      }
    ]
  },
  "successor": {
    "version": "v2027-og",
    "label": "2027\u20132028 Operating Guidelines (Post-2026 ROD Decision Framework)",
    "authority": "Colorado River Guidelines for Coordinated Operations of Lake Powell and Lake Mead, Operating Years 2027 and 2028 (August 2026), issued pursuant to the Record of Decision for the Decision Framework (2027\u20132036) \u00b7 Powell \u00a75.1, Mead \u00a75.3, ICS \u00a75.4, Mexico \u00a75.6. ROD issuance date (2026-08-21) per Reclamation's post-2026 operations page, retrieved 2026-08-25 \u2014 the guidelines PDF itself carries only 'August 2026'.",
    "effectiveFrom": "2026-10-01",
    "effectiveTo": "2028-12-31",
    "status": "issued",
    "trigger": "Powell: Most Probable AUGUST 24-Month Study projection of the OCTOBER 1 elevation for the coming Water Year (monthly Most Probable projections govern in-year adjustments). Mead: a fixed August determination for the following Calendar Year \u2014 no elevation tiers.",
    "criticalElevations": {
      "powell_dead_pool": 3370.0,
      "powell_min_power_pool": 3490.0,
      "powell_full_pool": 3700.0,
      "mead_dead_pool": 895.0,
      "mead_min_power_pool": 950.0,
      "mead_full_pool": 1229.0
    },
    "notes": [
      "The state apportionment split (AZ 2.04 / CA 3.96 / NV 0.25 MAF) is 'in accordance with a Lower Basin implementing agreement(s)' (\u00a75.3.A.2); absent executed agreements the Secretary determines the apportionment of the same 6.25 MAF total under applicable law (\u00a75.3.A.3).",
      "Reductions for Mexico are determined by the IBWC under 1944 Treaty Minutes, separate from and in addition to the \u00a75.3 apportionment (\u00a75.6). Minute 323 is, by its own terms, in effect through 2026-12-31 (source: IBWC Minute 323, not these guidelines); no successor Minute announced as of 2026-08-25.",
      "Effectiveness is conditional (\u00a73): the guidelines take effect upon (1) execution by the Secretary and (2) execution of the necessary implementing and parallel agreements; absent (2), the Secretary proceeds under the \u00a7\u00a75.2\u20135.4 default paths. The effective_from/effective_to span here is our reading of the Operating Years covered (Powell WY2027 begins 2026-10-01; Mead CY2028 ends 2028-12-31), not a verbatim document range.",
      "The guidelines confirm in a primary document that 3,490 ft is Lake Powell's minimum power pool (\u00a75.1) and that hydropower cannot be produced below 950 ft at Lake Mead (\u00a75.3) \u2014 both previously held at medium confidence from secondary sources.",
      "These guidelines are not a precedent for future operations (ROD \u00a710.11) and could be superseded during the Effective Period by consensus guidelines (\u00a73)."
    ],
    "powellRanges": [
      {
        "name": "Upper Elevation Range",
        "band": {
          "upper": null,
          "lower": 3565.0,
          "upperInclusive": true,
          "lowerInclusive": true,
          "wording": "projected October 1 elevation at or above 3,565 ft"
        },
        "releaseLadderAf": [
          8230000,
          8000000,
          7500000
        ],
        "note": "Evaluate 8.23, then 8.0, then 7.5 MAF; the initial release is the first projected to maintain 3,510 ft through the Water Year (\u00a75.1.A)."
      },
      {
        "name": "Mid-Elevation Range",
        "band": {
          "upper": 3565.0,
          "lower": 3540.0,
          "upperInclusive": false,
          "lowerInclusive": true,
          "wording": "projected October 1 elevation below 3,565 ft and at or above 3,540 ft"
        },
        "releaseLadderAf": [
          8000000,
          7500000,
          7000000
        ],
        "note": "Evaluate 8.0, then 7.5, then 7.0 MAF; the initial release is the first projected to maintain 3,510 ft through the Water Year (\u00a75.1.B)."
      },
      {
        "name": "Low Elevation Infrastructure Protection Range",
        "band": {
          "upper": 3540.0,
          "lower": null,
          "upperInclusive": false,
          "lowerInclusive": false,
          "wording": "projected October 1 elevation below 3,540 ft"
        },
        "releaseLadderAf": [
          7000000
        ],
        "note": "Assume 7.0 MAF; if that holds 3,510 ft, begin the year at 7.0. If not, defer the Water Year release determination to April and set it between 6.0 and 7.0 MAF per the \u00a75.1.C Table 1 process, coordinated with CRSP Upper Initial Unit drought releases."
      }
    ],
    "powellReleaseFloorAf": 6000000,
    "powellProtectionTargetFt": 3510.0,
    "powellCriticalFt": 3500.0,
    "powellUpwardAdjustAboveFt": 3565.0,
    "powellConsultHighFt": 3665.0,
    "powellContemplatedReleaseRangeAf": [
      5000000,
      12000000
    ],
    "meadCondition": "Shortage Condition (both Operating Years)",
    "meadTotalApportionmentAf": 6250000,
    "meadTotalReductionAf": 1250000,
    "meadApportionments": [
      {
        "party": "arizona",
        "apportionmentAf": 2040000,
        "reductionAf": 760000
      },
      {
        "party": "california",
        "apportionmentAf": 3960000,
        "reductionAf": 440000
      },
      {
        "party": "nevada",
        "apportionmentAf": 250000,
        "reductionAf": 50000
      }
    ],
    "additionalSystemConservationTotalAf": 700000,
    "meadConsultLowProjectedFt": 1010.0,
    "meadConsultRaiseApportionmentsFt": 1125.0,
    "icsNoDeliveryBelowJan1Ft": 1000.0,
    "icsConsultBandFt": [
      1000.0,
      1025.0
    ]
  },
  "successorVectors": [
    {
      "projectedOct1Elevation": 3400.0,
      "rangeName": "Low Elevation Infrastructure Protection Range",
      "releaseLadderAf": [
        7000000
      ],
      "releaseFloorAf": 6000000,
      "protectionTargetFt": 3510.0
    },
    {
      "projectedOct1Elevation": 3490.0,
      "rangeName": "Low Elevation Infrastructure Protection Range",
      "releaseLadderAf": [
        7000000
      ],
      "releaseFloorAf": 6000000,
      "protectionTargetFt": 3510.0
    },
    {
      "projectedOct1Elevation": 3500.0,
      "rangeName": "Low Elevation Infrastructure Protection Range",
      "releaseLadderAf": [
        7000000
      ],
      "releaseFloorAf": 6000000,
      "protectionTargetFt": 3510.0
    },
    {
      "projectedOct1Elevation": 3516.16,
      "rangeName": "Low Elevation Infrastructure Protection Range",
      "releaseLadderAf": [
        7000000
      ],
      "releaseFloorAf": 6000000,
      "protectionTargetFt": 3510.0
    },
    {
      "projectedOct1Elevation": 3539.99,
      "rangeName": "Low Elevation Infrastructure Protection Range",
      "releaseLadderAf": [
        7000000
      ],
      "releaseFloorAf": 6000000,
      "protectionTargetFt": 3510.0
    },
    {
      "projectedOct1Elevation": 3540.0,
      "rangeName": "Mid-Elevation Range",
      "releaseLadderAf": [
        8000000,
        7500000,
        7000000
      ],
      "releaseFloorAf": 6000000,
      "protectionTargetFt": 3510.0
    },
    {
      "projectedOct1Elevation": 3540.01,
      "rangeName": "Mid-Elevation Range",
      "releaseLadderAf": [
        8000000,
        7500000,
        7000000
      ],
      "releaseFloorAf": 6000000,
      "protectionTargetFt": 3510.0
    },
    {
      "projectedOct1Elevation": 3564.99,
      "rangeName": "Mid-Elevation Range",
      "releaseLadderAf": [
        8000000,
        7500000,
        7000000
      ],
      "releaseFloorAf": 6000000,
      "protectionTargetFt": 3510.0
    },
    {
      "projectedOct1Elevation": 3565.0,
      "rangeName": "Upper Elevation Range",
      "releaseLadderAf": [
        8230000,
        8000000,
        7500000
      ],
      "releaseFloorAf": 6000000,
      "protectionTargetFt": 3510.0
    },
    {
      "projectedOct1Elevation": 3565.01,
      "rangeName": "Upper Elevation Range",
      "releaseLadderAf": [
        8230000,
        8000000,
        7500000
      ],
      "releaseFloorAf": 6000000,
      "protectionTargetFt": 3510.0
    },
    {
      "projectedOct1Elevation": 3600.0,
      "rangeName": "Upper Elevation Range",
      "releaseLadderAf": [
        8230000,
        8000000,
        7500000
      ],
      "releaseFloorAf": 6000000,
      "protectionTargetFt": 3510.0
    }
  ]
} as const;
