-- GENERATED by packages/registry/codegen/generate.ts — DO NOT EDIT.
-- Source of truth: packages/registry/measures/**/*.yaml. Run `pnpm gen`.

CREATE TABLE IF NOT EXISTS measure (
  id                 text PRIMARY KEY,
  label              text NOT NULL,
  description        text,
  quantity_kind      text NOT NULL,
  canonical_unit     text NOT NULL,
  measurement_class  text NOT NULL,
  accounting_concept text NOT NULL,
  temporal_semantics text NOT NULL,
  grain              text NOT NULL,
  calendar           text NOT NULL,
  spatial_type       text NOT NULL,
  spatial_id         text NOT NULL,
  agency             text NOT NULL,
  source_system      text NOT NULL,
  endpoint           text NOT NULL,
  citation           text NOT NULL,
  revision_status    text NOT NULL,
  expected_cadence   text NOT NULL,
  sla_hours          double precision NOT NULL,
  caveats            jsonb NOT NULL DEFAULT '[]',
  not_comparable_with jsonb NOT NULL DEFAULT '[]'
);

INSERT INTO measure VALUES (
  'colorado.gauge.lees_ferry.discharge', 'Colorado River at Lees Ferry — discharge', 'Daily mean discharge at USGS gauge 09380000, the Colorado River Compact point dividing the Upper and Lower Basins. Continuous daily record since 1921-10-01. Also serves as the real-time downstream cross-check on Glen Canyon Dam releases.',
  'VolumeFlowRate', 'cubic_foot_per_second', 'observed',
  'flow', 'interval_mean', 'P1D', 'water_year',
  'gauge', 'usgs.09380000',
  'USGS', 'Water Data OGC API', 'https://api.waterdata.usgs.gov/ogcapi/v0/collections/daily/items?monitoring_location_id=USGS-09380000&parameter_code=00060',
  'U.S. Geological Survey, National Water Information System via Water Data OGC API, site 09380000 Colorado River at Lees Ferry, AZ, parameter 00060. Accessed {access_date}.', 'mixed',
  'P1D', 48,
  '["Daily mean of a fluctuating hydropower-driven flow; sub-daily swings are large.","Never use legacy waterservices.usgs.gov (decommissioning) or discontinued site 09379910 for this reach."]'::jsonb,
  '[{"measure":"colorado.reservoir.powell.release_total","reason":"Interval-mean rate (cfs) vs. interval-total volume (AF/day), measured ~15 miles apart with Paria River inflow between. Convertible only with explicit rate→volume conversion and reach caveats.\n"}]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  label = EXCLUDED.label, description = EXCLUDED.description,
  quantity_kind = EXCLUDED.quantity_kind, canonical_unit = EXCLUDED.canonical_unit,
  measurement_class = EXCLUDED.measurement_class, accounting_concept = EXCLUDED.accounting_concept,
  temporal_semantics = EXCLUDED.temporal_semantics, grain = EXCLUDED.grain, calendar = EXCLUDED.calendar,
  spatial_type = EXCLUDED.spatial_type, spatial_id = EXCLUDED.spatial_id,
  agency = EXCLUDED.agency, source_system = EXCLUDED.source_system, endpoint = EXCLUDED.endpoint,
  citation = EXCLUDED.citation, revision_status = EXCLUDED.revision_status,
  expected_cadence = EXCLUDED.expected_cadence, sla_hours = EXCLUDED.sla_hours,
  caveats = EXCLUDED.caveats, not_comparable_with = EXCLUDED.not_comparable_with;

INSERT INTO measure VALUES (
  'colorado.reservoir.mead.elevation', 'Lake Mead pool elevation', 'Water surface elevation of Lake Mead above mean sea level. The operative variable for shortage-tier determination (via projected January 1 elevation) and the critical thresholds at 1,075 / 1,050 / 1,025 ft (tiers), ~950 ft (minimum power pool), and 895 ft (dead pool).',
  'Length', 'foot', 'observed',
  'stage', 'instantaneous', 'P1D', 'water_year',
  'reservoir', 'usbr.lake_mead',
  'USBR', 'RISE', 'https://data.usbr.gov/rise/api/result?itemId=6123',
  'U.S. Bureau of Reclamation, RISE, Lake Mead pool elevation, catalog item 6123. Period of record from 1935-02-02. Accessed {access_date}.', 'provisional',
  'P1D', 36,
  '["Tier determination does not use current elevation: it uses the projected January 1 elevation from the August 24-Month Study. Displaying current elevation against tier thresholds requires that framing."]'::jsonb,
  '[{"measure":"colorado.reservoir.mead.storage","reason":"Elevation maps to storage only through the (re-surveyed, nonlinear) area-capacity table — never by linear scaling.\n"}]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  label = EXCLUDED.label, description = EXCLUDED.description,
  quantity_kind = EXCLUDED.quantity_kind, canonical_unit = EXCLUDED.canonical_unit,
  measurement_class = EXCLUDED.measurement_class, accounting_concept = EXCLUDED.accounting_concept,
  temporal_semantics = EXCLUDED.temporal_semantics, grain = EXCLUDED.grain, calendar = EXCLUDED.calendar,
  spatial_type = EXCLUDED.spatial_type, spatial_id = EXCLUDED.spatial_id,
  agency = EXCLUDED.agency, source_system = EXCLUDED.source_system, endpoint = EXCLUDED.endpoint,
  citation = EXCLUDED.citation, revision_status = EXCLUDED.revision_status,
  expected_cadence = EXCLUDED.expected_cadence, sla_hours = EXCLUDED.sla_hours,
  caveats = EXCLUDED.caveats, not_comparable_with = EXCLUDED.not_comparable_with;

INSERT INTO measure VALUES (
  'colorado.reservoir.mead.release_total', 'Hoover Dam total release', 'Total daily release volume from Hoover Dam — Lake Mead outflow toward the lower river reaches, downstream diversions, and ultimately Mexico.',
  'Volume', 'acre_foot', 'observed',
  'flow', 'interval_total', 'P1D', 'water_year',
  'reservoir', 'usbr.lake_mead',
  'USBR', 'RISE', 'https://data.usbr.gov/rise/api/result?itemId=6122',
  'U.S. Bureau of Reclamation, RISE, Hoover Dam total release (acre-feet), catalog item 6122. Accessed {access_date}.', 'provisional',
  'P1D', 36,
  '["RISE''s Mead record has no inflow or evaporation items; Mead inflow must be derived (Powell release + intervening gains) and evaporation estimated — both as separate measures with measurement_class reflecting the derivation.","Independent downstream cross-check: USGS 09421500 (below Hoover Dam)."]'::jsonb,
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  label = EXCLUDED.label, description = EXCLUDED.description,
  quantity_kind = EXCLUDED.quantity_kind, canonical_unit = EXCLUDED.canonical_unit,
  measurement_class = EXCLUDED.measurement_class, accounting_concept = EXCLUDED.accounting_concept,
  temporal_semantics = EXCLUDED.temporal_semantics, grain = EXCLUDED.grain, calendar = EXCLUDED.calendar,
  spatial_type = EXCLUDED.spatial_type, spatial_id = EXCLUDED.spatial_id,
  agency = EXCLUDED.agency, source_system = EXCLUDED.source_system, endpoint = EXCLUDED.endpoint,
  citation = EXCLUDED.citation, revision_status = EXCLUDED.revision_status,
  expected_cadence = EXCLUDED.expected_cadence, sla_hours = EXCLUDED.sla_hours,
  caveats = EXCLUDED.caveats, not_comparable_with = EXCLUDED.not_comparable_with;

INSERT INTO measure VALUES (
  'colorado.reservoir.mead.storage', 'Lake Mead storage', 'Volume of water held in Lake Mead, derived by Reclamation from measured pool elevation via the area-capacity table.',
  'Volume', 'acre_foot', 'observed',
  'storage', 'instantaneous', 'P1D', 'water_year',
  'reservoir', 'usbr.lake_mead',
  'USBR', 'RISE', 'https://data.usbr.gov/rise/api/result?itemId=6124',
  'U.S. Bureau of Reclamation, Reclamation Information Sharing Environment (RISE), Lake Mead storage, catalog item 6124. Accessed {access_date}.', 'provisional',
  'P1D', 36,
  '["Storage is derived from elevation via an area-capacity table that is periodically re-surveyed; sedimentation shifts the curve over decades, so deep-historical storage values are not strictly comparable to modern ones."]'::jsonb,
  '[{"measure":"colorado.upper_basin.consumptive_use","reason":"Stock vs. flux. Same unit, different kind of quantity."},{"measure":"colorado.state.arizona.allocation","reason":"Allocation is a legal entitlement, not a measurement. Meaningful only as \"use vs. entitlement\" — never as a sum or a shared total.\n"}]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  label = EXCLUDED.label, description = EXCLUDED.description,
  quantity_kind = EXCLUDED.quantity_kind, canonical_unit = EXCLUDED.canonical_unit,
  measurement_class = EXCLUDED.measurement_class, accounting_concept = EXCLUDED.accounting_concept,
  temporal_semantics = EXCLUDED.temporal_semantics, grain = EXCLUDED.grain, calendar = EXCLUDED.calendar,
  spatial_type = EXCLUDED.spatial_type, spatial_id = EXCLUDED.spatial_id,
  agency = EXCLUDED.agency, source_system = EXCLUDED.source_system, endpoint = EXCLUDED.endpoint,
  citation = EXCLUDED.citation, revision_status = EXCLUDED.revision_status,
  expected_cadence = EXCLUDED.expected_cadence, sla_hours = EXCLUDED.sla_hours,
  caveats = EXCLUDED.caveats, not_comparable_with = EXCLUDED.not_comparable_with;

INSERT INTO measure VALUES (
  'colorado.reservoir.powell.elevation', 'Lake Powell pool elevation', 'Water surface elevation of Lake Powell above mean sea level. The operative variable for release-tier determination (via projected January 1 elevation), with critical thresholds at 3,575 / 3,525 ft (tier boundaries), 3,490 ft (minimum power pool, medium confidence), and 3,370 ft (dead pool).',
  'Length', 'foot', 'observed',
  'stage', 'instantaneous', 'P1D', 'water_year',
  'reservoir', 'usbr.lake_powell',
  'USBR', 'RISE', 'https://data.usbr.gov/rise/api/result?itemId=508',
  'U.S. Bureau of Reclamation, RISE, Lake Powell pool elevation, catalog item 508. Accessed {access_date}.', 'provisional',
  'P1D', 36,
  '["Tier determination uses the projected January 1 elevation from the August 24-Month Study, not current elevation."]'::jsonb,
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  label = EXCLUDED.label, description = EXCLUDED.description,
  quantity_kind = EXCLUDED.quantity_kind, canonical_unit = EXCLUDED.canonical_unit,
  measurement_class = EXCLUDED.measurement_class, accounting_concept = EXCLUDED.accounting_concept,
  temporal_semantics = EXCLUDED.temporal_semantics, grain = EXCLUDED.grain, calendar = EXCLUDED.calendar,
  spatial_type = EXCLUDED.spatial_type, spatial_id = EXCLUDED.spatial_id,
  agency = EXCLUDED.agency, source_system = EXCLUDED.source_system, endpoint = EXCLUDED.endpoint,
  citation = EXCLUDED.citation, revision_status = EXCLUDED.revision_status,
  expected_cadence = EXCLUDED.expected_cadence, sla_hours = EXCLUDED.sla_hours,
  caveats = EXCLUDED.caveats, not_comparable_with = EXCLUDED.not_comparable_with;

INSERT INTO measure VALUES (
  'colorado.reservoir.powell.inflow_unregulated', 'Lake Powell unregulated inflow', 'Inflow to Lake Powell adjusted by Reclamation to remove the effects of upstream reservoir operations (Flaming Gorge, Blue Mesa, Navajo). The standard measure of what the Upper Basin actually produced, and the target variable of CBRFC seasonal forecasts.',
  'Volume', 'acre_foot', 'estimated',
  'flow', 'interval_total', 'P1D', 'water_year',
  'reservoir', 'usbr.lake_powell',
  'USBR', 'RISE', 'https://data.usbr.gov/rise/api/result?itemId=4301',
  'U.S. Bureau of Reclamation, RISE, Lake Powell unregulated inflow, catalog item 4301. Accessed {access_date}.', 'provisional',
  'P1D', 48,
  '["\"Unregulated\" is a computed abstraction, not a gauge reading — it removes upstream reservoir effects but not upstream consumptive use. It is NOT natural flow. Item id 4301 assumed from catalog research; verify item 4288 vs 4301 (regulated vs unregulated, af) on first ingest."]'::jsonb,
  '[{"measure":"colorado.gauge.lees_ferry.discharge_natural","reason":"Unregulated inflow removes reservoir operations only; naturalized flow also adds back upstream consumptive use. Different abstractions.\n"}]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  label = EXCLUDED.label, description = EXCLUDED.description,
  quantity_kind = EXCLUDED.quantity_kind, canonical_unit = EXCLUDED.canonical_unit,
  measurement_class = EXCLUDED.measurement_class, accounting_concept = EXCLUDED.accounting_concept,
  temporal_semantics = EXCLUDED.temporal_semantics, grain = EXCLUDED.grain, calendar = EXCLUDED.calendar,
  spatial_type = EXCLUDED.spatial_type, spatial_id = EXCLUDED.spatial_id,
  agency = EXCLUDED.agency, source_system = EXCLUDED.source_system, endpoint = EXCLUDED.endpoint,
  citation = EXCLUDED.citation, revision_status = EXCLUDED.revision_status,
  expected_cadence = EXCLUDED.expected_cadence, sla_hours = EXCLUDED.sla_hours,
  caveats = EXCLUDED.caveats, not_comparable_with = EXCLUDED.not_comparable_with;

INSERT INTO measure VALUES (
  'colorado.reservoir.powell.release_total', 'Glen Canyon Dam total release', 'Total daily release volume from Glen Canyon Dam (powerplant plus bypass and spillway), i.e. Lake Powell outflow to the Grand Canyon reach and, ultimately, Lake Mead.',
  'Volume', 'acre_foot', 'observed',
  'flow', 'interval_total', 'P1D', 'water_year',
  'reservoir', 'usbr.lake_powell',
  'USBR', 'RISE', 'https://data.usbr.gov/rise/api/result?itemId=4354',
  'U.S. Bureau of Reclamation, RISE, Glen Canyon Dam total release (acre-feet), catalog item 4354. Accessed {access_date}.', 'provisional',
  'P1D', 36,
  '["Annual release volumes are set by tier rules but revisable mid-year: WY2026 was reduced from 7.48 to 6.00 MAF in April 2026 under SEIS ROD §6.E.","No active USGS gauge exists immediately below the dam (09379910 was discontinued 2004-08-02); Lees Ferry (09380000), ~15 miles downstream, is the independent observational cross-check."]'::jsonb,
  '[{"measure":"colorado.gauge.lees_ferry.discharge","reason":"Related but not identical: Lees Ferry is ~15 miles downstream with intervening Paria River inflow and reach effects, and is an interval-mean rate (cfs) rather than an interval-total volume.\n"}]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  label = EXCLUDED.label, description = EXCLUDED.description,
  quantity_kind = EXCLUDED.quantity_kind, canonical_unit = EXCLUDED.canonical_unit,
  measurement_class = EXCLUDED.measurement_class, accounting_concept = EXCLUDED.accounting_concept,
  temporal_semantics = EXCLUDED.temporal_semantics, grain = EXCLUDED.grain, calendar = EXCLUDED.calendar,
  spatial_type = EXCLUDED.spatial_type, spatial_id = EXCLUDED.spatial_id,
  agency = EXCLUDED.agency, source_system = EXCLUDED.source_system, endpoint = EXCLUDED.endpoint,
  citation = EXCLUDED.citation, revision_status = EXCLUDED.revision_status,
  expected_cadence = EXCLUDED.expected_cadence, sla_hours = EXCLUDED.sla_hours,
  caveats = EXCLUDED.caveats, not_comparable_with = EXCLUDED.not_comparable_with;

INSERT INTO measure VALUES (
  'colorado.reservoir.powell.storage', 'Lake Powell storage', 'Volume of water held in Lake Powell, derived by Reclamation from measured pool elevation via the area-capacity table.',
  'Volume', 'acre_foot', 'observed',
  'storage', 'instantaneous', 'P1D', 'water_year',
  'reservoir', 'usbr.lake_powell',
  'USBR', 'RISE', 'https://data.usbr.gov/rise/api/result?itemId=509',
  'U.S. Bureau of Reclamation, RISE, Lake Powell storage, catalog item 509. Accessed {access_date}.', 'provisional',
  'P1D', 36,
  '["Sedimentation since 1963 has reduced actual capacity below the nominal 24.32 MAF; percent-full figures depend on which capacity survey is used."]'::jsonb,
  '[{"measure":"colorado.upper_basin.consumptive_use","reason":"Stock vs. flux. Same unit, different kind of quantity."}]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  label = EXCLUDED.label, description = EXCLUDED.description,
  quantity_kind = EXCLUDED.quantity_kind, canonical_unit = EXCLUDED.canonical_unit,
  measurement_class = EXCLUDED.measurement_class, accounting_concept = EXCLUDED.accounting_concept,
  temporal_semantics = EXCLUDED.temporal_semantics, grain = EXCLUDED.grain, calendar = EXCLUDED.calendar,
  spatial_type = EXCLUDED.spatial_type, spatial_id = EXCLUDED.spatial_id,
  agency = EXCLUDED.agency, source_system = EXCLUDED.source_system, endpoint = EXCLUDED.endpoint,
  citation = EXCLUDED.citation, revision_status = EXCLUDED.revision_status,
  expected_cadence = EXCLUDED.expected_cadence, sla_hours = EXCLUDED.sla_hours,
  caveats = EXCLUDED.caveats, not_comparable_with = EXCLUDED.not_comparable_with;

INSERT INTO measure VALUES (
  'colorado.snow.stations.swe', 'SNOTEL station snow water equivalent', 'Daily snow water equivalent at individual SNOTEL stations in the Upper Colorado Basin HUCs. The raw input to the basin percent-of-median rollup and the hydrology model''s SWE features. Station dimension carried in geography_id (one observation row per station per day).',
  'Length', 'millimeter', 'observed',
  'snowpack', 'instantaneous', 'P1D', 'water_year',
  'basin', 'colorado.upper_basin',
  'USDA-NRCS', 'AWDB REST', 'https://wcc.sc.egov.usda.gov/awdbRestApi/services/v1/data',
  'USDA Natural Resources Conservation Service, Air and Water Database (AWDB), SNOTEL network, element WTEQ. Accessed {access_date}.', 'provisional',
  'P1D', 48,
  '["Source unit is inches; converted to canonical millimeters at ingest.","Station set changes over time (new stations, discontinuations); the stations endpoint''s beginDate/endDate and HUC membership are synced as a dimension, not assumed static."]'::jsonb,
  '[]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  label = EXCLUDED.label, description = EXCLUDED.description,
  quantity_kind = EXCLUDED.quantity_kind, canonical_unit = EXCLUDED.canonical_unit,
  measurement_class = EXCLUDED.measurement_class, accounting_concept = EXCLUDED.accounting_concept,
  temporal_semantics = EXCLUDED.temporal_semantics, grain = EXCLUDED.grain, calendar = EXCLUDED.calendar,
  spatial_type = EXCLUDED.spatial_type, spatial_id = EXCLUDED.spatial_id,
  agency = EXCLUDED.agency, source_system = EXCLUDED.source_system, endpoint = EXCLUDED.endpoint,
  citation = EXCLUDED.citation, revision_status = EXCLUDED.revision_status,
  expected_cadence = EXCLUDED.expected_cadence, sla_hours = EXCLUDED.sla_hours,
  caveats = EXCLUDED.caveats, not_comparable_with = EXCLUDED.not_comparable_with;

INSERT INTO measure VALUES (
  'colorado.snow.upper_basin.swe_pct_median', 'Upper Basin snowpack — percent of median SWE', 'Snow water equivalent across Upper Colorado Basin SNOTEL stations as a percent of the 1991–2020 median for the date. COMPUTED BY US from station-level AWDB data plus HUC membership — NRCS publishes this only as a map product, not an API. Methodology replicates NRCS practice; deviations are documented in the computation module and surfaced here.',
  'Dimensionless', 'percent', 'estimated',
  'snowpack', 'instantaneous', 'P1D', 'water_year',
  'basin', 'colorado.upper_basin',
  'USDA-NRCS (stations); Basin (aggregation)', 'AWDB REST + basin computation', 'https://wcc.sc.egov.usda.gov/awdbRestApi/services/v1/data',
  'Computed from USDA NRCS AWDB SNOTEL station data (snow water equivalent, element WTEQ) aggregated over Upper Colorado Basin HUCs against 1991–2020 station medians. Basin project computation. Accessed {access_date}.', 'provisional',
  'P1D', 48,
  '["This is OUR aggregation, not the NRCS number. Reconciliation against the NRCS map product is a standing asset check with a stated tolerance; divergence beyond tolerance fails the pipeline, not silently ships.","Percent-of-median is undefined when the median approaches zero (early autumn, mid-summer); the computation returns null outside the snow season rather than an unstable ratio. Missing is not zero.","SNOTEL coverage begins in the late 1970s; the network densified over time."]'::jsonb,
  '[{"measure":"colorado.reservoir.powell.inflow_unregulated","reason":"Snowpack percent does not map linearly to runoff volume — runoff efficiency varies with temperature, soil moisture, and dust; that relationship is exactly what the hydrology model estimates.\n"}]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  label = EXCLUDED.label, description = EXCLUDED.description,
  quantity_kind = EXCLUDED.quantity_kind, canonical_unit = EXCLUDED.canonical_unit,
  measurement_class = EXCLUDED.measurement_class, accounting_concept = EXCLUDED.accounting_concept,
  temporal_semantics = EXCLUDED.temporal_semantics, grain = EXCLUDED.grain, calendar = EXCLUDED.calendar,
  spatial_type = EXCLUDED.spatial_type, spatial_id = EXCLUDED.spatial_id,
  agency = EXCLUDED.agency, source_system = EXCLUDED.source_system, endpoint = EXCLUDED.endpoint,
  citation = EXCLUDED.citation, revision_status = EXCLUDED.revision_status,
  expected_cadence = EXCLUDED.expected_cadence, sla_hours = EXCLUDED.sla_hours,
  caveats = EXCLUDED.caveats, not_comparable_with = EXCLUDED.not_comparable_with;

INSERT INTO measure VALUES (
  'colorado.structure.grand_valley_canal.diversion', 'Grand Valley Canal — headgate diversion', 'Daily flow diverted from the Colorado River into the Grand Valley Canal (WDID 7200645, Mesa County), measured at the headgate and recorded by Colorado''s water commissioners. Water rights on this canal date to 1882. The first structure-level (farm-scale) series in the registry.',
  'VolumeFlowRate', 'cubic_foot_per_second', 'observed',
  'diversion', 'interval_mean', 'P1D', 'water_year',
  'station', 'codwr.7200645',
  'Colorado Division of Water Resources', 'CDSS REST API', 'https://dwr.state.co.us/Rest/GET/api/v2/structures/divrec/divrecday/?wdid=7200645',
  'Colorado Division of Water Resources, Colorado''s Decision Support Systems (CDSS), daily diversion records for WDID 7200645 (Grand Valley Canal), irrigation water class. Accessed {access_date}.', 'provisional',
  'P1D', 72,
  '["This is a DIVERSION at one headgate, not consumptive use — return flows from the Grand Valley re-enter the river downstream.","One headgate carries multiple water classes (irrigation plus a small stock/domestic class); this measure is the irrigation class only. Summing all classes at a WDID double-counts.","The canal is a mutual-company structure serving many farms; attribution below the headgate is not knowable from public records."]'::jsonb,
  '[{"measure":"colorado.upper_basin.consumptive_use","reason":"Diversion vs. consumptive use — return flows make these different quantities."}]'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  label = EXCLUDED.label, description = EXCLUDED.description,
  quantity_kind = EXCLUDED.quantity_kind, canonical_unit = EXCLUDED.canonical_unit,
  measurement_class = EXCLUDED.measurement_class, accounting_concept = EXCLUDED.accounting_concept,
  temporal_semantics = EXCLUDED.temporal_semantics, grain = EXCLUDED.grain, calendar = EXCLUDED.calendar,
  spatial_type = EXCLUDED.spatial_type, spatial_id = EXCLUDED.spatial_id,
  agency = EXCLUDED.agency, source_system = EXCLUDED.source_system, endpoint = EXCLUDED.endpoint,
  citation = EXCLUDED.citation, revision_status = EXCLUDED.revision_status,
  expected_cadence = EXCLUDED.expected_cadence, sla_hours = EXCLUDED.sla_hours,
  caveats = EXCLUDED.caveats, not_comparable_with = EXCLUDED.not_comparable_with;
