/**
 * Registry codegen — the mechanism that makes measures/*.yaml the single
 * source of truth. Reads every measure, validates against the JSON Schema,
 * then emits generated artifacts for each downstream consumer:
 *
 *   packages/contracts/src/measures.gen.ts   TS types + const map (frontend/API)
 *   packages/model/basin_model/measures_gen.py  typed dicts (Python model/ingest)
 *   db/seed/measures.gen.sql                 measure dimension upsert
 *
 * Never hand-edit generated files. Run `pnpm gen` after any YAML change;
 * `pnpm gen:check` (CI) fails if committed artifacts drift from the YAML.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { globSync } from "node:fs";
import { parse } from "yaml";
import { Ajv2020 } from "ajv/dist/2020.js";
import addFormatsModule from "ajv-formats";

// ajv-formats ships CJS; under NodeNext ESM interop the callable may sit on
// .default at runtime while the namespace type is non-callable — normalize.
type AddFormatsFn = (ajv: InstanceType<typeof Ajv2020>) => unknown;
const _afm = addFormatsModule as unknown as AddFormatsFn & { default?: AddFormatsFn };
const addFormats: AddFormatsFn = _afm.default ?? _afm;

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..", "..");
const REGISTRY = join(ROOT, "packages", "registry");
const CHECK = process.argv.includes("--check");

// ---------- load + validate ----------

const schema = JSON.parse(
  readFileSync(join(REGISTRY, "schema", "measure.schema.json"), "utf8"),
);
const ajv = new Ajv2020({ allErrors: true, allowUnionTypes: true });
addFormats(ajv);
const validate = ajv.compile(schema);

interface Measure {
  id: string;
  label: string;
  description?: string;
  aliases?: string[];
  quantity_kind: string;
  canonical_unit: string;
  measurement_class: string;
  accounting_concept: string;
  temporal_semantics: string;
  grain: string;
  calendar: string;
  spatial_ref: { type: string; id: string };
  provenance: Record<string, unknown> & { citation: string };
  ingest?: { adapter: string; params?: Record<string, unknown>; source_unit?: string; depends_on?: string[] };
  revision_policy: { status: string; detect_via?: string; note?: string };
  freshness: { expected_cadence: string; sla_hours: number; note?: string };
  uncertainty?: string;
  caveats?: string[];
  not_comparable_with?: { measure: string; reason: string }[];
}

const files = globSync(join(REGISTRY, "measures", "**", "*.yaml")).sort();
if (files.length === 0) throw new Error("No measure YAML files found");

const measures: Measure[] = [];
const errors: string[] = [];
for (const f of files) {
  const doc = parse(readFileSync(f, "utf8")) as Measure;
  if (!validate(doc)) {
    errors.push(
      `${relative(ROOT, f)}:\n` +
        (validate.errors ?? [])
          .map((e) => `   ${e.instancePath || "$"}: ${e.message}`)
          .join("\n"),
    );
    continue;
  }
  measures.push(doc);
}
if (errors.length) {
  console.error(`Schema validation failed for ${errors.length} file(s):\n${errors.join("\n")}`);
  process.exit(1);
}

// Cross-file integrity: unique ids; not_comparable_with targets must exist
// (or be declared as known-future via a leading id match failure warning).
const ids = new Set<string>();
for (const m of measures) {
  if (ids.has(m.id)) {
    console.error(`Duplicate measure id: ${m.id}`);
    process.exit(1);
  }
  ids.add(m.id);
}
const danglingEdges: string[] = [];
for (const m of measures) {
  for (const edge of m.not_comparable_with ?? []) {
    if (!ids.has(edge.measure)) danglingEdges.push(`${m.id} -> ${edge.measure}`);
  }
}
if (danglingEdges.length) {
  // Dangling edges are allowed (they mark measures worth authoring later)
  // but surfaced loudly so they never go stale silently.
  console.warn(`⚠ not_comparable_with edges referencing not-yet-authored measures:\n   ${danglingEdges.join("\n   ")}`);
}

const banner = (comment: string) =>
  `${comment} GENERATED by packages/registry/codegen/generate.ts — DO NOT EDIT.\n${comment} Source of truth: packages/registry/measures/**/*.yaml. Run \`pnpm gen\`.\n`;

const outputs: { path: string; content: string }[] = [];

// ---------- TypeScript contracts ----------

const enumOf = (key: keyof Measure) =>
  [...new Set(measures.map((m) => m[key] as string))].sort();

const tsUnion = (values: string[]) => values.map((v) => JSON.stringify(v)).join(" | ");

const ts = `${banner("//")}
export type MeasurementClass = ${tsUnion(schema.properties.measurement_class.enum)};
export type AccountingConcept = ${tsUnion(schema.properties.accounting_concept.enum)};
export type TemporalSemantics = ${tsUnion(schema.properties.temporal_semantics.enum)};
export type CanonicalUnit = ${tsUnion(schema.properties.canonical_unit.enum)};
export type QuantityKind = ${tsUnion(schema.properties.quantity_kind.enum)};
export type Calendar = ${tsUnion(schema.properties.calendar.enum)};

export interface MeasureDef {
  readonly id: string;
  readonly label: string;
  readonly description?: string;
  readonly quantityKind: QuantityKind;
  readonly canonicalUnit: CanonicalUnit;
  readonly measurementClass: MeasurementClass;
  readonly accountingConcept: AccountingConcept;
  readonly temporalSemantics: TemporalSemantics;
  readonly grain: string;
  readonly calendar: Calendar;
  readonly spatialRef: { readonly type: string; readonly id: string };
  readonly provenance: { readonly agency: string; readonly system: string; readonly endpoint: string; readonly citation: string };
  readonly revisionStatus: string;
  readonly freshness: { readonly expectedCadence: string; readonly slaHours: number };
  readonly uncertainty?: string;
  readonly caveats: readonly string[];
  readonly notComparableWith: readonly { readonly measure: string; readonly reason: string }[];
}

export type MeasureId = ${tsUnion(measures.map((m) => m.id))};

export const MEASURES: Record<MeasureId, MeasureDef> = {
${measures
  .map((m) => {
    const def = {
      id: m.id,
      label: m.label,
      description: m.description?.trim(),
      quantityKind: m.quantity_kind,
      canonicalUnit: m.canonical_unit,
      measurementClass: m.measurement_class,
      accountingConcept: m.accounting_concept,
      temporalSemantics: m.temporal_semantics,
      grain: m.grain,
      calendar: m.calendar,
      spatialRef: m.spatial_ref,
      provenance: {
        agency: m.provenance.agency,
        system: m.provenance.system,
        endpoint: m.provenance.endpoint,
        citation: (m.provenance.citation as string).trim(),
      },
      revisionStatus: m.revision_policy.status,
      freshness: { expectedCadence: m.freshness.expected_cadence, slaHours: m.freshness.sla_hours },
      uncertainty: m.uncertainty,
      caveats: (m.caveats ?? []).map((c) => c.trim()),
      notComparableWith: (m.not_comparable_with ?? []).map((e) => ({ measure: e.measure, reason: e.reason.trim() })),
    };
    return `  ${JSON.stringify(m.id)}: ${JSON.stringify(def, null, 2).replace(/\n/g, "\n  ")},`;
  })
  .join("\n")}
};

/**
 * Guard: measures whose accounting concepts differ may not be summed or
 * directly compared. Returns the declared human-readable reason when the
 * pair is explicitly marked incomparable, or a generic concept-mismatch
 * reason; null when the combination is allowed.
 */
export function incomparabilityReason(a: MeasureId, b: MeasureId): string | null {
  if (a === b) return null;
  const ma = MEASURES[a];
  const mb = MEASURES[b];
  const declared =
    ma.notComparableWith.find((e) => e.measure === b) ??
    mb.notComparableWith.find((e) => e.measure === a);
  if (declared) return declared.reason;
  if (ma.accountingConcept !== mb.accountingConcept)
    return \`Different accounting concepts: \${ma.accountingConcept} vs \${mb.accountingConcept}. Combining them requires a declared bridge.\`;
  if (ma.temporalSemantics !== mb.temporalSemantics)
    return \`Different temporal semantics: \${ma.temporalSemantics} vs \${mb.temporalSemantics}. Aggregation across them is undefined.\`;
  return null;
}
`;
outputs.push({ path: join(ROOT, "packages", "contracts", "src", "measures.gen.ts"), content: ts });

// ---------- Python module ----------

/** Serialize a JSON-safe value as a Python literal (None/True/False aware). */
const pyLit = (v: unknown): string => {
  if (v === null || v === undefined) return "None";
  if (v === true) return "True";
  if (v === false) return "False";
  if (typeof v === "number") return String(v);
  if (typeof v === "string") return JSON.stringify(v);
  if (Array.isArray(v)) return `[${v.map(pyLit).join(", ")}]`;
  return `{${Object.entries(v as Record<string, unknown>)
    .map(([k, val]) => `${JSON.stringify(k)}: ${pyLit(val)}`)
    .join(", ")}}`;
};

const py = `${banner("#")}
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class MeasureDef:
    id: str
    label: str
    quantity_kind: str
    canonical_unit: str
    measurement_class: str
    accounting_concept: str
    temporal_semantics: str
    grain: str
    calendar: str
    spatial_type: str
    spatial_id: str
    agency: str
    system: str
    endpoint: str
    citation: str
    revision_status: str
    expected_cadence: str
    sla_hours: float
    ingest_adapter: str | None = None
    ingest_params: dict = field(default_factory=dict)
    source_unit: str | None = None
    depends_on: tuple[str, ...] = ()
    caveats: tuple[str, ...] = ()


MEASURES: dict[str, MeasureDef] = {
${measures
  .map((m) => {
    const p = pyLit;
    return `    ${p(m.id)}: MeasureDef(
        id=${p(m.id)},
        label=${p(m.label)},
        quantity_kind=${p(m.quantity_kind)},
        canonical_unit=${p(m.canonical_unit)},
        measurement_class=${p(m.measurement_class)},
        accounting_concept=${p(m.accounting_concept)},
        temporal_semantics=${p(m.temporal_semantics)},
        grain=${p(m.grain)},
        calendar=${p(m.calendar)},
        spatial_type=${p(m.spatial_ref.type)},
        spatial_id=${p(m.spatial_ref.id)},
        agency=${p(m.provenance.agency)},
        system=${p(m.provenance.system)},
        endpoint=${p(m.provenance.endpoint)},
        citation=${p((m.provenance.citation as string).trim())},
        revision_status=${p(m.revision_policy.status)},
        expected_cadence=${p(m.freshness.expected_cadence)},
        sla_hours=${m.freshness.sla_hours},
        ingest_adapter=${p(m.ingest?.adapter ?? null)},
        ingest_params=${pyLit(m.ingest?.params ?? {})},
        source_unit=${p(m.ingest?.source_unit ?? null)},
        depends_on=(${(m.ingest?.depends_on ?? []).map((d) => JSON.stringify(d) + ",").join(" ")}),
        caveats=(${(m.caveats ?? []).map((c) => JSON.stringify(c.trim()) + ",").join(" ")}),
    ),`;
  })
  .join("\n")}
}
`;
outputs.push({ path: join(ROOT, "packages", "model", "basin_model", "measures_gen.py"), content: py });

// ---------- SQL seed ----------

const sqlEscape = (s: string | undefined | null) =>
  s == null ? "NULL" : `'${s.replace(/'/g, "''")}'`;

const sql = `${banner("--")}
CREATE TABLE IF NOT EXISTS measure (
  id                 text PRIMARY KEY,
  label              text NOT NULL,
  description        text,
  quantity_kind      text NOT NULL,
  canonical_unit     text NOT NULL,
  measurement_class  text NOT NULL,
  accounting_concept text NOT NULL,
  temporal_semantics text NOT NULL,
  grain              text NOT NULL,
  calendar           text NOT NULL,
  spatial_type       text NOT NULL,
  spatial_id         text NOT NULL,
  agency             text NOT NULL,
  source_system      text NOT NULL,
  endpoint           text NOT NULL,
  citation           text NOT NULL,
  revision_status    text NOT NULL,
  expected_cadence   text NOT NULL,
  sla_hours          double precision NOT NULL,
  caveats            jsonb NOT NULL DEFAULT '[]',
  not_comparable_with jsonb NOT NULL DEFAULT '[]'
);

${measures
  .map(
    (m) => `INSERT INTO measure VALUES (
  ${sqlEscape(m.id)}, ${sqlEscape(m.label)}, ${sqlEscape(m.description?.trim())},
  ${sqlEscape(m.quantity_kind)}, ${sqlEscape(m.canonical_unit)}, ${sqlEscape(m.measurement_class)},
  ${sqlEscape(m.accounting_concept)}, ${sqlEscape(m.temporal_semantics)}, ${sqlEscape(m.grain)}, ${sqlEscape(m.calendar)},
  ${sqlEscape(m.spatial_ref.type)}, ${sqlEscape(m.spatial_ref.id)},
  ${sqlEscape(m.provenance.agency as string)}, ${sqlEscape(m.provenance.system as string)}, ${sqlEscape(m.provenance.endpoint as string)},
  ${sqlEscape((m.provenance.citation as string).trim())}, ${sqlEscape(m.revision_policy.status)},
  ${sqlEscape(m.freshness.expected_cadence)}, ${m.freshness.sla_hours},
  ${sqlEscape(JSON.stringify((m.caveats ?? []).map((c) => c.trim())))}::jsonb,
  ${sqlEscape(JSON.stringify(m.not_comparable_with ?? []))}::jsonb
) ON CONFLICT (id) DO UPDATE SET
  label = EXCLUDED.label, description = EXCLUDED.description,
  quantity_kind = EXCLUDED.quantity_kind, canonical_unit = EXCLUDED.canonical_unit,
  measurement_class = EXCLUDED.measurement_class, accounting_concept = EXCLUDED.accounting_concept,
  temporal_semantics = EXCLUDED.temporal_semantics, grain = EXCLUDED.grain, calendar = EXCLUDED.calendar,
  spatial_type = EXCLUDED.spatial_type, spatial_id = EXCLUDED.spatial_id,
  agency = EXCLUDED.agency, source_system = EXCLUDED.source_system, endpoint = EXCLUDED.endpoint,
  citation = EXCLUDED.citation, revision_status = EXCLUDED.revision_status,
  expected_cadence = EXCLUDED.expected_cadence, sla_hours = EXCLUDED.sla_hours,
  caveats = EXCLUDED.caveats, not_comparable_with = EXCLUDED.not_comparable_with;`,
  )
  .join("\n\n")}
`;
outputs.push({ path: join(ROOT, "db", "seed", "measures.gen.sql"), content: sql });

// ---------- write or check ----------

let drift = false;
for (const out of outputs) {
  mkdirSync(dirname(out.path), { recursive: true });
  if (CHECK) {
    const existing = existsSync(out.path) ? readFileSync(out.path, "utf8") : "";
    if (existing !== out.content) {
      console.error(`DRIFT: ${relative(ROOT, out.path)} is stale — run \`pnpm gen\``);
      drift = true;
    }
  } else {
    writeFileSync(out.path, out.content);
    console.log(`wrote ${relative(ROOT, out.path)}`);
  }
}
if (CHECK && drift) process.exit(1);
console.log(`${CHECK ? "checked" : "generated"} ${outputs.length} artifacts from ${measures.length} measures`);
