/**
 * Rights schema codegen — schema/right.schema.json is the single source of
 * truth for the normalized water-right record (rights-v1). Emits:
 *
 *   packages/contracts/src/rights.gen.ts        TS types + schema const
 *   packages/ingest/basin_ingest/rights_gen.py  Literals + schema dict + validate()
 *
 * Run via `pnpm gen`; `pnpm gen:check` (CI) fails on drift. Same doctrine as
 * generate.ts for measures: never hand-edit generated files.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { Ajv2020 } from "ajv/dist/2020.js";
import addFormatsModule from "ajv-formats";

type AddFormatsFn = (ajv: InstanceType<typeof Ajv2020>) => unknown;
const _afm = addFormatsModule as unknown as AddFormatsFn & { default?: AddFormatsFn };
const addFormats: AddFormatsFn = _afm.default ?? _afm;

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..", "..", "..");
const SCHEMA_PATH = join(__dirname, "..", "schema", "right.schema.json");

type Prop = {
  enum?: (string | null)[];
  items?: { enum?: string[] };
  const?: string;
  type?: string | string[];
  description?: string;
};
const schema = JSON.parse(readFileSync(SCHEMA_PATH, "utf8")) as {
  properties: Record<string, Prop>;
  required: string[];
};

// The schema must itself be valid JSON Schema 2020-12.
const ajv = new Ajv2020({ strict: false, allowUnionTypes: true });
addFormats(ajv);
ajv.compile(schema);

const P = schema.properties;
const enumVals = (name: string): (string | null)[] =>
  P[name]!.enum ?? P[name]!.items!.enum!;
const tsUnion = (vals: (string | null)[]) =>
  vals.map((v) => (v === null ? "null" : JSON.stringify(v))).join(" | ");
const pyLiteral = (vals: (string | null)[]) =>
  `Literal[${vals.filter((v) => v !== null).map((v) => JSON.stringify(v)).join(", ")}]`;

const ENUM_FIELDS = [
  "state",
  "loc_quality",
  "priority_basis",
  "owner_entity_class",
  "status_class",
  "quantity_unit",
  "quantity_kind",
] as const;
const USE_CLASSES = enumVals("use_classes") as string[];
const VERSION = P.schema_version!.const!;

const HEADER = `GENERATED by packages/registry/codegen/generate-rights.ts — DO NOT EDIT.
Source of truth: packages/registry/schema/right.schema.json (${VERSION}).`;

// ---------- TypeScript ----------
let ts = `/**\n * ${HEADER.split("\n").join("\n * ")}\n */\n\n`;
for (const f of ENUM_FIELDS) {
  const name = f.replace(/(^|_)(\w)/g, (_, __, c: string) => c.toUpperCase());
  ts += `export type ${name} = ${tsUnion(enumVals(f))};\n`;
}
ts += `export type UseClass = ${tsUnion(USE_CLASSES)};\n\n`;
ts += `export const RIGHTS_SCHEMA_VERSION = ${JSON.stringify(VERSION)} as const;\n\n`;
ts += `export interface NormalizedWaterRight {
  right_uid: string;
  state: State;
  source_system: string;
  source_id: string;
  lon: number | null;
  lat: number | null;
  loc_quality: LocQuality;
  priority_date: string | null;
  priority_basis: PriorityBasis;
  use_classes: UseClass[];
  quantity_value: number | null;
  quantity_unit: QuantityUnit;
  quantity_kind: QuantityKind;
  owner_name_raw: string | null;
  owner_entity_class: OwnerEntityClass;
  status_class: StatusClass;
  status_raw: string | null;
  source_url: string;
  fetched: string;
  schema_version: typeof RIGHTS_SCHEMA_VERSION;
}\n\n`;
ts += `/** The full JSON Schema, for runtime validation at artifact boundaries. */\n`;
ts += `export const RIGHT_JSON_SCHEMA = ${JSON.stringify(schema, null, 2)} as const;\n`;

// ---------- Python ----------
const pyDict = (v: unknown): string => {
  if (v === null) return "None";
  if (typeof v === "boolean") return v ? "True" : "False";
  if (typeof v === "number" || typeof v === "string") return JSON.stringify(v);
  if (Array.isArray(v)) return `[${v.map(pyDict).join(", ")}]`;
  return `{${Object.entries(v as object)
    .map(([k, val]) => `${JSON.stringify(k)}: ${pyDict(val)}`)
    .join(", ")}}`;
};
let py = `"""${HEADER}"""\n\nfrom typing import Literal, TypedDict\n\n`;
py += `RIGHTS_SCHEMA_VERSION = ${JSON.stringify(VERSION)}\n\n`;
for (const f of ENUM_FIELDS) {
  const name = f.toUpperCase();
  py += `${name} = ${pyLiteral(enumVals(f))}\n`;
}
py += `USE_CLASS = ${pyLiteral(USE_CLASSES)}\n\n`;
py += `class NormalizedWaterRight(TypedDict):\n`;
const pyType: Record<string, string> = {
  right_uid: "str", state: "STATE", source_system: "str", source_id: "str",
  lon: "float | None", lat: "float | None", loc_quality: "LOC_QUALITY",
  priority_date: "str | None", priority_basis: "PRIORITY_BASIS",
  use_classes: "list[USE_CLASS]", quantity_value: "float | None",
  quantity_unit: "QUANTITY_UNIT | None", quantity_kind: "QUANTITY_KIND | None",
  owner_name_raw: "str | None", owner_entity_class: "OWNER_ENTITY_CLASS",
  status_class: "STATUS_CLASS", status_raw: "str | None",
  source_url: "str", fetched: "str", schema_version: "str",
};
for (const [k, t] of Object.entries(pyType)) py += `    ${k}: ${t}\n`;
py += `\nRIGHT_JSON_SCHEMA = ${pyDict(schema)}\n\n`;
py += `_REQUIRED = ${pyDict(schema.required)}\n
_ENUMS = {${ENUM_FIELDS.map((f) => `${JSON.stringify(f)}: ${pyDict(enumVals(f))}`).join(", ")}, "use_classes": ${pyDict(USE_CLASSES)}}\n

def validate_right(row: dict) -> list[str]:
    """Cheap structural validation (no external deps): returns a list of
    problems, empty when valid. Full JSON-Schema validation can be layered
    on via RIGHT_JSON_SCHEMA where the jsonschema package is available."""
    problems = []
    for k in _REQUIRED:
        if row.get(k) in (None, ""):
            problems.append(f"missing required field: {k}")
    for field, allowed in _ENUMS.items():
        v = row.get(field)
        if v is None:
            continue
        vals = v if isinstance(v, list) else [v]
        for item in vals:
            if item is not None and item not in allowed:
                problems.append(f"{field}: {item!r} not in vocabulary")
    if row.get("schema_version") != RIGHTS_SCHEMA_VERSION:
        problems.append(f"schema_version must be {RIGHTS_SCHEMA_VERSION}")
    return problems\n`;

// ---------- write / check ----------
const outputs = [
  { path: join(ROOT, "packages", "contracts", "src", "rights.gen.ts"), content: ts },
  { path: join(ROOT, "packages", "ingest", "basin_ingest", "rights_gen.py"), content: py },
];
const check = process.argv.includes("--check");
let drift = false;
for (const out of outputs) {
  if (check) {
    let current = "";
    try { current = readFileSync(out.path, "utf8"); } catch { /* missing = drift */ }
    if (current !== out.content) { console.error(`DRIFT: ${out.path}`); drift = true; }
  } else {
    writeFileSync(out.path, out.content);
    console.log(`wrote ${out.path}`);
  }
}
if (check && drift) process.exit(1);
if (check) console.log("rights codegen: no drift");
